/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.tencent;

public final class ErrorCode {
  public final static ErrorCode OK = new ErrorCode("OK", 0);
  public final static ErrorCode ERR_INVALID_PARAM = new ErrorCode("ERR_INVALID_PARAM", 10001);
  public final static ErrorCode ERR_WRONG_STATE = new ErrorCode("ERR_WRONG_STATE", 10002);
  public final static ErrorCode ERR_MEMORY_FAILED = new ErrorCode("ERR_MEMORY_FAILED", 10003);
  public final static ErrorCode ERR_UNKNOWN = new ErrorCode("ERR_UNKNOWN", 19999);

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ErrorCode swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ErrorCode.class + " with value " + swigValue);
  }

  private ErrorCode(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ErrorCode(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ErrorCode(String swigName, ErrorCode swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ErrorCode[] swigValues = { OK, ERR_INVALID_PARAM, ERR_WRONG_STATE, ERR_MEMORY_FAILED, ERR_UNKNOWN };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

