/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.tencent;

public final class ExpectedAudioType {
  public final static ExpectedAudioType kStereo = new ExpectedAudioType("kStereo", 2);
  public final static ExpectedAudioType kMono = new ExpectedAudioType("kMono", 1);
  public final static ExpectedAudioType kAuto = new ExpectedAudioType("kAuto", 0);

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ExpectedAudioType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ExpectedAudioType.class + " with value " + swigValue);
  }

  private ExpectedAudioType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ExpectedAudioType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ExpectedAudioType(String swigName, ExpectedAudioType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ExpectedAudioType[] swigValues = { kStereo, kMono, kAuto };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

