/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.tencent;

public class ITRTCMediaRecorder {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ITRTCMediaRecorder(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ITRTCMediaRecorder obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        trtcenginewarperJNI.delete_ITRTCMediaRecorder(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCallback(ITRTCMediaRecorderCallback callback) {
    trtcenginewarperJNI.ITRTCMediaRecorder_setCallback(swigCPtr, this, ITRTCMediaRecorderCallback.getCPtr(callback), callback);
  }

  public boolean setParam(long sdkappid, String roomid, String userId, int output, String dir) {
    return trtcenginewarperJNI.ITRTCMediaRecorder_setParam(swigCPtr, this, sdkappid, roomid, userId, output, dir);
  }

  public void addAudioFrame(String userId, TRTCAudioFrame frame) {
    trtcenginewarperJNI.ITRTCMediaRecorder_addAudioFrame(swigCPtr, this, userId, TRTCAudioFrame.getCPtr(frame), frame);
  }

  public void addVideoFrame(String userId, TRTCVideoStreamType streamType, TRTCVideoFrame frame) {
    trtcenginewarperJNI.ITRTCMediaRecorder_addVideoFrame(swigCPtr, this, userId, streamType.swigValue(), TRTCVideoFrame.getCPtr(frame), frame);
  }

  public void stopOne(String userId) {
    trtcenginewarperJNI.ITRTCMediaRecorder_stopOne(swigCPtr, this, userId);
  }

  public void stopAll() {
    trtcenginewarperJNI.ITRTCMediaRecorder_stopAll(swigCPtr, this);
  }

}
