/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.tencent;

public class ITRTCImage {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ITRTCImage(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ITRTCImage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        trtcenginewarperJNI.delete_ITRTCImage(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void SetCallback(ITRTCImageCallback callback) {
    trtcenginewarperJNI.ITRTCImage_SetCallback(swigCPtr, this, ITRTCImageCallback.getCPtr(callback), callback);
  }

  public int WriteImage(TRTCVideoFrame frame, String file_path, ImageType type) {
    return trtcenginewarperJNI.ITRTCImage_WriteImage(swigCPtr, this, TRTCVideoFrame.getCPtr(frame), frame, file_path, type.swigValue());
  }

}
