/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.tencent;

public class ITRTCMediaRecorderCallback {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ITRTCMediaRecorderCallback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ITRTCMediaRecorderCallback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        trtcenginewarperJNI.delete_ITRTCMediaRecorderCallback(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    trtcenginewarperJNI.ITRTCMediaRecorderCallback_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    trtcenginewarperJNI.ITRTCMediaRecorderCallback_change_ownership(this, swigCPtr, true);
  }

  public void onFinished(String userId, int output, String filepath) {
    if (getClass() == ITRTCMediaRecorderCallback.class) trtcenginewarperJNI.ITRTCMediaRecorderCallback_onFinished(swigCPtr, this, userId, output, filepath); else trtcenginewarperJNI.ITRTCMediaRecorderCallback_onFinishedSwigExplicitITRTCMediaRecorderCallback(swigCPtr, this, userId, output, filepath);
  }

  public ITRTCMediaRecorderCallback() {
    this(trtcenginewarperJNI.new_ITRTCMediaRecorderCallback(), true);
    trtcenginewarperJNI.ITRTCMediaRecorderCallback_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
