/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.tencent;

public class ITRTCCloudCallback {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ITRTCCloudCallback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ITRTCCloudCallback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        trtcenginewarperJNI.delete_ITRTCCloudCallback(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    trtcenginewarperJNI.ITRTCCloudCallback_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    trtcenginewarperJNI.ITRTCCloudCallback_change_ownership(this, swigCPtr, true);
  }

  public void onError(TXLiteAVError errCode, String errMsg, SWIGTYPE_p_void arg) {
    trtcenginewarperJNI.ITRTCCloudCallback_onError(swigCPtr, this, errCode.swigValue(), errMsg, SWIGTYPE_p_void.getCPtr(arg));
  }

  public void onWarning(TXLiteAVWarning warningCode, String warningMsg, SWIGTYPE_p_void arg) {
    trtcenginewarperJNI.ITRTCCloudCallback_onWarning(swigCPtr, this, warningCode.swigValue(), warningMsg, SWIGTYPE_p_void.getCPtr(arg));
  }

  public void onEnterRoom(java.math.BigInteger elapsed) {
    trtcenginewarperJNI.ITRTCCloudCallback_onEnterRoom(swigCPtr, this, elapsed);
  }

  public void onExitRoom(int reason) {
    trtcenginewarperJNI.ITRTCCloudCallback_onExitRoom(swigCPtr, this, reason);
  }

  public void onUserEnter(String userId) {
    trtcenginewarperJNI.ITRTCCloudCallback_onUserEnter(swigCPtr, this, userId);
  }

  public void onUserExit(String userId, int reason) {
    trtcenginewarperJNI.ITRTCCloudCallback_onUserExit(swigCPtr, this, userId, reason);
  }

  public void onFirstVideoFrame(String userId, long width, long height) {
    if (getClass() == ITRTCCloudCallback.class) trtcenginewarperJNI.ITRTCCloudCallback_onFirstVideoFrame(swigCPtr, this, userId, width, height); else trtcenginewarperJNI.ITRTCCloudCallback_onFirstVideoFrameSwigExplicitITRTCCloudCallback(swigCPtr, this, userId, width, height);
  }

  public void onFirstAudioFrame(String userId) {
    if (getClass() == ITRTCCloudCallback.class) trtcenginewarperJNI.ITRTCCloudCallback_onFirstAudioFrame(swigCPtr, this, userId); else trtcenginewarperJNI.ITRTCCloudCallback_onFirstAudioFrameSwigExplicitITRTCCloudCallback(swigCPtr, this, userId);
  }

  public void onFirstSubStreamFrame(String userId, long width, long height) {
    if (getClass() == ITRTCCloudCallback.class) trtcenginewarperJNI.ITRTCCloudCallback_onFirstSubStreamFrame(swigCPtr, this, userId, width, height); else trtcenginewarperJNI.ITRTCCloudCallback_onFirstSubStreamFrameSwigExplicitITRTCCloudCallback(swigCPtr, this, userId, width, height);
  }

  public void onUserVideoAvailable(String userId, boolean available) {
    if (getClass() == ITRTCCloudCallback.class) trtcenginewarperJNI.ITRTCCloudCallback_onUserVideoAvailable(swigCPtr, this, userId, available); else trtcenginewarperJNI.ITRTCCloudCallback_onUserVideoAvailableSwigExplicitITRTCCloudCallback(swigCPtr, this, userId, available);
  }

  public void onUserAudioAvailable(String userId, boolean available) {
    if (getClass() == ITRTCCloudCallback.class) trtcenginewarperJNI.ITRTCCloudCallback_onUserAudioAvailable(swigCPtr, this, userId, available); else trtcenginewarperJNI.ITRTCCloudCallback_onUserAudioAvailableSwigExplicitITRTCCloudCallback(swigCPtr, this, userId, available);
  }

  public void onUserSubStreamAvailable(String userId, boolean available) {
    if (getClass() == ITRTCCloudCallback.class) trtcenginewarperJNI.ITRTCCloudCallback_onUserSubStreamAvailable(swigCPtr, this, userId, available); else trtcenginewarperJNI.ITRTCCloudCallback_onUserSubStreamAvailableSwigExplicitITRTCCloudCallback(swigCPtr, this, userId, available);
  }

  public void onRecvSEIMsg(String userId, SWIGTYPE_p_unsigned_char data, int datalen) {
    if (getClass() == ITRTCCloudCallback.class) trtcenginewarperJNI.ITRTCCloudCallback_onRecvSEIMsg(swigCPtr, this, userId, SWIGTYPE_p_unsigned_char.getCPtr(data), datalen); else trtcenginewarperJNI.ITRTCCloudCallback_onRecvSEIMsgSwigExplicitITRTCCloudCallback(swigCPtr, this, userId, SWIGTYPE_p_unsigned_char.getCPtr(data), datalen);
  }

  public void onRecvCustomCmdMsg(String userId, int cmdId, int seq, SWIGTYPE_p_unsigned_char msg, int msglen) {
    if (getClass() == ITRTCCloudCallback.class) trtcenginewarperJNI.ITRTCCloudCallback_onRecvCustomCmdMsg(swigCPtr, this, userId, cmdId, seq, SWIGTYPE_p_unsigned_char.getCPtr(msg), msglen); else trtcenginewarperJNI.ITRTCCloudCallback_onRecvCustomCmdMsgSwigExplicitITRTCCloudCallback(swigCPtr, this, userId, cmdId, seq, SWIGTYPE_p_unsigned_char.getCPtr(msg), msglen);
  }

  public void onMissCustomCmdMsg(String userId, int cmdId, int errCode, int missed) {
    if (getClass() == ITRTCCloudCallback.class) trtcenginewarperJNI.ITRTCCloudCallback_onMissCustomCmdMsg(swigCPtr, this, userId, cmdId, errCode, missed); else trtcenginewarperJNI.ITRTCCloudCallback_onMissCustomCmdMsgSwigExplicitITRTCCloudCallback(swigCPtr, this, userId, cmdId, errCode, missed);
  }

  public void onConnectionLost() {
    if (getClass() == ITRTCCloudCallback.class) trtcenginewarperJNI.ITRTCCloudCallback_onConnectionLost(swigCPtr, this); else trtcenginewarperJNI.ITRTCCloudCallback_onConnectionLostSwigExplicitITRTCCloudCallback(swigCPtr, this);
  }

  public void onTryToReconnect() {
    if (getClass() == ITRTCCloudCallback.class) trtcenginewarperJNI.ITRTCCloudCallback_onTryToReconnect(swigCPtr, this); else trtcenginewarperJNI.ITRTCCloudCallback_onTryToReconnectSwigExplicitITRTCCloudCallback(swigCPtr, this);
  }

  public void onConnectionRecovery() {
    if (getClass() == ITRTCCloudCallback.class) trtcenginewarperJNI.ITRTCCloudCallback_onConnectionRecovery(swigCPtr, this); else trtcenginewarperJNI.ITRTCCloudCallback_onConnectionRecoverySwigExplicitITRTCCloudCallback(swigCPtr, this);
  }

  public ITRTCCloudCallback() {
    this(trtcenginewarperJNI.new_ITRTCCloudCallback(), true);
    trtcenginewarperJNI.ITRTCCloudCallback_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
