/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.tencent;

public class ITRTCDecryptionCallback {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ITRTCDecryptionCallback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ITRTCDecryptionCallback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        trtcenginewarperJNI.delete_ITRTCDecryptionCallback(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    trtcenginewarperJNI.ITRTCDecryptionCallback_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    trtcenginewarperJNI.ITRTCDecryptionCallback_change_ownership(this, swigCPtr, true);
  }

  public boolean onAudioFrameDecrypt(String userId, TRTCCustomEncryptionData data) {
    return (getClass() == ITRTCDecryptionCallback.class) ? trtcenginewarperJNI.ITRTCDecryptionCallback_onAudioFrameDecrypt(swigCPtr, this, userId, TRTCCustomEncryptionData.getCPtr(data), data) : trtcenginewarperJNI.ITRTCDecryptionCallback_onAudioFrameDecryptSwigExplicitITRTCDecryptionCallback(swigCPtr, this, userId, TRTCCustomEncryptionData.getCPtr(data), data);
  }

  public boolean onVideoFrameDecrypt(String userId, TRTCVideoStreamType streamType, TRTCCustomEncryptionData data) {
    return (getClass() == ITRTCDecryptionCallback.class) ? trtcenginewarperJNI.ITRTCDecryptionCallback_onVideoFrameDecrypt(swigCPtr, this, userId, streamType.swigValue(), TRTCCustomEncryptionData.getCPtr(data), data) : trtcenginewarperJNI.ITRTCDecryptionCallback_onVideoFrameDecryptSwigExplicitITRTCDecryptionCallback(swigCPtr, this, userId, streamType.swigValue(), TRTCCustomEncryptionData.getCPtr(data), data);
  }

  public ITRTCDecryptionCallback() {
    this(trtcenginewarperJNI.new_ITRTCDecryptionCallback(), true);
    trtcenginewarperJNI.ITRTCDecryptionCallback_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
