/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.tencent;

public class ITRTCLogCallback {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ITRTCLogCallback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ITRTCLogCallback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        trtcenginewarperJNI.delete_ITRTCLogCallback(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    trtcenginewarperJNI.ITRTCLogCallback_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    trtcenginewarperJNI.ITRTCLogCallback_change_ownership(this, swigCPtr, true);
  }

  public void onLog(String log, TRTCLogLevel level, String module) {
    if (getClass() == ITRTCLogCallback.class) trtcenginewarperJNI.ITRTCLogCallback_onLog(swigCPtr, this, log, level.swigValue(), module); else trtcenginewarperJNI.ITRTCLogCallback_onLogSwigExplicitITRTCLogCallback(swigCPtr, this, log, level.swigValue(), module);
  }

  public ITRTCLogCallback() {
    this(trtcenginewarperJNI.new_ITRTCLogCallback(), true);
    trtcenginewarperJNI.ITRTCLogCallback_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
