/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.tencent;

public class ITRTCMediaPusher {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ITRTCMediaPusher(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ITRTCMediaPusher obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        trtcenginewarperJNI.delete_ITRTCMediaPusher(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void SetCallback(ITRTCMediaPusherCallback callback) {
    trtcenginewarperJNI.ITRTCMediaPusher_SetCallback(swigCPtr, this, ITRTCMediaPusherCallback.getCPtr(callback), callback);
  }

  public void StartWithConfig(PushConfig config) {
    trtcenginewarperJNI.ITRTCMediaPusher_StartWithConfig(swigCPtr, this, PushConfig.getCPtr(config), config);
  }

  public void Stop() {
    trtcenginewarperJNI.ITRTCMediaPusher_Stop(swigCPtr, this);
  }

  public void PushMedia(String url, String id) {
    trtcenginewarperJNI.ITRTCMediaPusher_PushMedia(swigCPtr, this, url, id);
  }

  public void SetWatermarkPath(String png_path) {
    trtcenginewarperJNI.ITRTCMediaPusher_SetWatermarkPath(swigCPtr, this, png_path);
  }

  public void SetWatermarkLocation(float left, float top, float mark_width) {
    trtcenginewarperJNI.ITRTCMediaPusher_SetWatermarkLocation(swigCPtr, this, left, top, mark_width);
  }

  public boolean IsWatermarkValid() {
    return trtcenginewarperJNI.ITRTCMediaPusher_IsWatermarkValid(swigCPtr, this);
  }

  public void Pause() {
    trtcenginewarperJNI.ITRTCMediaPusher_Pause(swigCPtr, this);
  }

  public void Resume() {
    trtcenginewarperJNI.ITRTCMediaPusher_Resume(swigCPtr, this);
  }

  public void Seek(int position) {
    trtcenginewarperJNI.ITRTCMediaPusher_Seek(swigCPtr, this, position);
  }

}
