/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.tencent;

public class ITRTCMediaMixerCallback {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ITRTCMediaMixerCallback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ITRTCMediaMixerCallback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        trtcenginewarperJNI.delete_ITRTCMediaMixerCallback(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    trtcenginewarperJNI.ITRTCMediaMixerCallback_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    trtcenginewarperJNI.ITRTCMediaMixerCallback_change_ownership(this, swigCPtr, true);
  }

  public void onMixedAudioFrame(TRTCAudioFrame frame) {
    trtcenginewarperJNI.ITRTCMediaMixerCallback_onMixedAudioFrame(swigCPtr, this, TRTCAudioFrame.getCPtr(frame), frame);
  }

  public void onMixedVideoFrame(TRTCVideoFrame frame) {
    trtcenginewarperJNI.ITRTCMediaMixerCallback_onMixedVideoFrame(swigCPtr, this, TRTCVideoFrame.getCPtr(frame), frame);
  }

  public void onError(int errcode, String errmsg) {
    trtcenginewarperJNI.ITRTCMediaMixerCallback_onError(swigCPtr, this, errcode, errmsg);
  }

  public ITRTCMediaMixerCallback() {
    this(trtcenginewarperJNI.new_ITRTCMediaMixerCallback(), true);
    trtcenginewarperJNI.ITRTCMediaMixerCallback_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
