/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.tencent;

public class ITRTCImageCallback {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ITRTCImageCallback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ITRTCImageCallback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        trtcenginewarperJNI.delete_ITRTCImageCallback(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    trtcenginewarperJNI.ITRTCImageCallback_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    trtcenginewarperJNI.ITRTCImageCallback_change_ownership(this, swigCPtr, true);
  }

  public void OnWriteComplete(String file_path, ImageType type, boolean is_ok) {
    trtcenginewarperJNI.ITRTCImageCallback_OnWriteComplete(swigCPtr, this, file_path, type.swigValue(), is_ok);
  }

  public ITRTCImageCallback() {
    this(trtcenginewarperJNI.new_ITRTCImageCallback(), true);
    trtcenginewarperJNI.ITRTCImageCallback_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
