/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.tencent;

public class ITRTCEncryptionCallback {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ITRTCEncryptionCallback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ITRTCEncryptionCallback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        trtcenginewarperJNI.delete_ITRTCEncryptionCallback(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    trtcenginewarperJNI.ITRTCEncryptionCallback_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    trtcenginewarperJNI.ITRTCEncryptionCallback_change_ownership(this, swigCPtr, true);
  }

  public boolean onAudioFrameEncrypt(TRTCCustomEncryptionData data) {
    return (getClass() == ITRTCEncryptionCallback.class) ? trtcenginewarperJNI.ITRTCEncryptionCallback_onAudioFrameEncrypt(swigCPtr, this, TRTCCustomEncryptionData.getCPtr(data), data) : trtcenginewarperJNI.ITRTCEncryptionCallback_onAudioFrameEncryptSwigExplicitITRTCEncryptionCallback(swigCPtr, this, TRTCCustomEncryptionData.getCPtr(data), data);
  }

  public boolean onVideoFrameEncrypt(TRTCVideoStreamType streamType, TRTCCustomEncryptionData data) {
    return (getClass() == ITRTCEncryptionCallback.class) ? trtcenginewarperJNI.ITRTCEncryptionCallback_onVideoFrameEncrypt(swigCPtr, this, streamType.swigValue(), TRTCCustomEncryptionData.getCPtr(data), data) : trtcenginewarperJNI.ITRTCEncryptionCallback_onVideoFrameEncryptSwigExplicitITRTCEncryptionCallback(swigCPtr, this, streamType.swigValue(), TRTCCustomEncryptionData.getCPtr(data), data);
  }

  public ITRTCEncryptionCallback() {
    this(trtcenginewarperJNI.new_ITRTCEncryptionCallback(), true);
    trtcenginewarperJNI.ITRTCEncryptionCallback_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
