/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.tencent;

public final class MediaPushError {
  public final static MediaPushError kNoError = new MediaPushError("kNoError", 0);
  public final static MediaPushError kAccountError = new MediaPushError("kAccountError", 1);
  public final static MediaPushError kFileError = new MediaPushError("kFileError", 2);
  public final static MediaPushError kNetworkError = new MediaPushError("kNetworkError", 3);
  public final static MediaPushError kInternalError = new MediaPushError("kInternalError", 4);

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static MediaPushError swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + MediaPushError.class + " with value " + swigValue);
  }

  private MediaPushError(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private MediaPushError(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private MediaPushError(String swigName, MediaPushError swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static MediaPushError[] swigValues = { kNoError, kAccountError, kFileError, kNetworkError, kInternalError };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

