/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.tencent;

public final class OutputFileType {
  public final static OutputFileType OUTFILE_TYPE_AUDIO = new OutputFileType("OUTFILE_TYPE_AUDIO", 0x00000001);
  public final static OutputFileType OUTFILE_TYPE_VIDEO = new OutputFileType("OUTFILE_TYPE_VIDEO", 0x00000002);
  public final static OutputFileType OUTFILE_TYPE_AUDIO_VIDEO = new OutputFileType("OUTFILE_TYPE_AUDIO_VIDEO", 0x00000004);

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static OutputFileType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + OutputFileType.class + " with value " + swigValue);
  }

  private OutputFileType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private OutputFileType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private OutputFileType(String swigName, OutputFileType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static OutputFileType[] swigValues = { OUTFILE_TYPE_AUDIO, OUTFILE_TYPE_VIDEO, OUTFILE_TYPE_AUDIO_VIDEO };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

