/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.tencent;

public final class PushContent {
  public final static PushContent kAudio = new PushContent("kAudio", 1);
  public final static PushContent kVideo = new PushContent("kVideo", 2);
  public final static PushContent kAudioAndVideo = new PushContent("kAudioAndVideo", 3);

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static PushContent swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + PushContent.class + " with value " + swigValue);
  }

  private PushContent(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private PushContent(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private PushContent(String swigName, PushContent swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static PushContent[] swigValues = { kAudio, kVideo, kAudioAndVideo };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

