/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.tencent;

public class PushConfig {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected PushConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PushConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        trtcenginewarperJNI.delete_PushConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRoom_param(TRTCParams value) {
    trtcenginewarperJNI.PushConfig_room_param_set(swigCPtr, this, TRTCParams.getCPtr(value), value);
  }

  public TRTCParams getRoom_param() {
    long cPtr = trtcenginewarperJNI.PushConfig_room_param_get(swigCPtr, this);
    return (cPtr == 0) ? null : new TRTCParams(cPtr, false);
  }

  public void setPush_content(PushContent value) {
    trtcenginewarperJNI.PushConfig_push_content_set(swigCPtr, this, value.swigValue());
  }

  public PushContent getPush_content() {
    return PushContent.swigToEnum(trtcenginewarperJNI.PushConfig_push_content_get(swigCPtr, this));
  }

  public void setRaw_h264(boolean value) {
    trtcenginewarperJNI.PushConfig_raw_h264_set(swigCPtr, this, value);
  }

  public boolean getRaw_h264() {
    return trtcenginewarperJNI.PushConfig_raw_h264_get(swigCPtr, this);
  }

  public void setSence(PushScene value) {
    trtcenginewarperJNI.PushConfig_sence_set(swigCPtr, this, value.swigValue());
  }

  public PushScene getSence() {
    return PushScene.swigToEnum(trtcenginewarperJNI.PushConfig_sence_get(swigCPtr, this));
  }

  public void setIs_repeat_last_pic_when_pausing(boolean value) {
    trtcenginewarperJNI.PushConfig_is_repeat_last_pic_when_pausing_set(swigCPtr, this, value);
  }

  public boolean getIs_repeat_last_pic_when_pausing() {
    return trtcenginewarperJNI.PushConfig_is_repeat_last_pic_when_pausing_get(swigCPtr, this);
  }

  public void setAudio_channels(ExpectedAudioType value) {
    trtcenginewarperJNI.PushConfig_audio_channels_set(swigCPtr, this, value.swigValue());
  }

  public ExpectedAudioType getAudio_channels() {
    return ExpectedAudioType.swigToEnum(trtcenginewarperJNI.PushConfig_audio_channels_get(swigCPtr, this));
  }

  public PushConfig() {
    this(trtcenginewarperJNI.new_PushConfig(), true);
  }

}
