/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.tencent;

public final class RegionOption {
  public final static RegionOption REGION_OPTION_FILLMODE_FIT = new RegionOption("REGION_OPTION_FILLMODE_FIT", 1 << 1);
  public final static RegionOption REGION_OPTION_FILLMODE_FULL = new RegionOption("REGION_OPTION_FILLMODE_FULL", 1 << 2);

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static RegionOption swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + RegionOption.class + " with value " + swigValue);
  }

  private RegionOption(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private RegionOption(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private RegionOption(String swigName, RegionOption swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static RegionOption[] swigValues = { REGION_OPTION_FILLMODE_FIT, REGION_OPTION_FILLMODE_FULL };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

