/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.tencent;

public class StringBuffer {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected StringBuffer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StringBuffer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        trtcenginewarperJNI.delete_StringBuffer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBuffer(String value) {
    trtcenginewarperJNI.StringBuffer_buffer_set(swigCPtr, this, value);
  }

  public String getBuffer() {
    return trtcenginewarperJNI.StringBuffer_buffer_get(swigCPtr, this);
  }

  public void setBuffer_len(long value) {
    trtcenginewarperJNI.StringBuffer_buffer_len_set(swigCPtr, this, value);
  }

  public long getBuffer_len() {
    return trtcenginewarperJNI.StringBuffer_buffer_len_get(swigCPtr, this);
  }

  public StringBuffer() {
    this(trtcenginewarperJNI.new_StringBuffer(), true);
  }

}
