/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.tencent;

public class TRTCCustomEncryptionData {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected TRTCCustomEncryptionData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TRTCCustomEncryptionData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        trtcenginewarperJNI.delete_TRTCCustomEncryptionData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setUnEncryptedData(byte[] value) {
    trtcenginewarperJNI.TRTCCustomEncryptionData_unEncryptedData_set(swigCPtr, this, value);
  }

  public byte[] getUnEncryptedData() {
    return trtcenginewarperJNI.TRTCCustomEncryptionData_unEncryptedData_get(swigCPtr, this);
}

  public void setUnEncryptedDataLength(long value) {
    trtcenginewarperJNI.TRTCCustomEncryptionData_unEncryptedDataLength_set(swigCPtr, this, value);
  }

  public long getUnEncryptedDataLength() {
    return trtcenginewarperJNI.TRTCCustomEncryptionData_unEncryptedDataLength_get(swigCPtr, this);
  }

  public void setEncryptedData(byte[] value) {
    trtcenginewarperJNI.TRTCCustomEncryptionData_EncryptedData_set(swigCPtr, this, value);
  }

  public byte[] getEncryptedData() {
    return trtcenginewarperJNI.TRTCCustomEncryptionData_EncryptedData_get(swigCPtr, this);
}

  public void setEncryptedDataLength(long value) {
    trtcenginewarperJNI.TRTCCustomEncryptionData_EncryptedDataLength_set(swigCPtr, this, value);
  }

  public long getEncryptedDataLength() {
    return trtcenginewarperJNI.TRTCCustomEncryptionData_EncryptedDataLength_get(swigCPtr, this);
  }

  public TRTCCustomEncryptionData() {
    this(trtcenginewarperJNI.new_TRTCCustomEncryptionData(), true);
  }

  public void setIs_encryption_buffer_setted(boolean value) {
    trtcenginewarperJNI.TRTCCustomEncryptionData_is_encryption_buffer_setted_set(swigCPtr, this, value);
  }

  public boolean getIs_encryption_buffer_setted() {
    return trtcenginewarperJNI.TRTCCustomEncryptionData_is_encryption_buffer_setted_get(swigCPtr, this);
  }

  public void setIs_decryption_buffer_setted(boolean value) {
    trtcenginewarperJNI.TRTCCustomEncryptionData_is_decryption_buffer_setted_set(swigCPtr, this, value);
  }

  public boolean getIs_decryption_buffer_setted() {
    return trtcenginewarperJNI.TRTCCustomEncryptionData_is_decryption_buffer_setted_get(swigCPtr, this);
  }

  public void initEncryptionData(int data_length_init) {
    trtcenginewarperJNI.TRTCCustomEncryptionData_initEncryptionData(swigCPtr, this, data_length_init);
  }

  public void initUnEncryptionData(int data_length_init) {
    trtcenginewarperJNI.TRTCCustomEncryptionData_initUnEncryptionData(swigCPtr, this, data_length_init);
  }

}
