/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.tencent;

public final class TRTCVideoStreamType {
  public final static TRTCVideoStreamType TRTCVideoStreamTypeBig = new TRTCVideoStreamType("TRTCVideoStreamTypeBig", 0);
  public final static TRTCVideoStreamType TRTCVideoStreamTypeSmall = new TRTCVideoStreamType("TRTCVideoStreamTypeSmall", 1);
  public final static TRTCVideoStreamType TRTCVideoStreamTypeSub = new TRTCVideoStreamType("TRTCVideoStreamTypeSub", 2);

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static TRTCVideoStreamType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + TRTCVideoStreamType.class + " with value " + swigValue);
  }

  private TRTCVideoStreamType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private TRTCVideoStreamType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private TRTCVideoStreamType(String swigName, TRTCVideoStreamType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static TRTCVideoStreamType[] swigValues = { TRTCVideoStreamTypeBig, TRTCVideoStreamTypeSmall, TRTCVideoStreamTypeSub };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

