/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.tencent;

public final class TRTCAudioFrameFormat {
  public final static TRTCAudioFrameFormat TRTCAudioFrameFormat_Unknown = new TRTCAudioFrameFormat("TRTCAudioFrameFormat_Unknown", 0);
  public final static TRTCAudioFrameFormat TRTCAudioFrameFormat_PCM = new TRTCAudioFrameFormat("TRTCAudioFrameFormat_PCM", 1);
  public final static TRTCAudioFrameFormat TRTCAudioFrameFormat_AAC = new TRTCAudioFrameFormat("TRTCAudioFrameFormat_AAC", 2);
  public final static TRTCAudioFrameFormat TRTCAudioFrameFormat_PCM_16KHZ_MONO = new TRTCAudioFrameFormat("TRTCAudioFrameFormat_PCM_16KHZ_MONO", 3);
  public final static TRTCAudioFrameFormat TRTCAudioFrameFormat_PCM_8KHZ_MONO = new TRTCAudioFrameFormat("TRTCAudioFrameFormat_PCM_8KHZ_MONO", 4);

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static TRTCAudioFrameFormat swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + TRTCAudioFrameFormat.class + " with value " + swigValue);
  }

  private TRTCAudioFrameFormat(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private TRTCAudioFrameFormat(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private TRTCAudioFrameFormat(String swigName, TRTCAudioFrameFormat swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static TRTCAudioFrameFormat[] swigValues = { TRTCAudioFrameFormat_Unknown, TRTCAudioFrameFormat_PCM, TRTCAudioFrameFormat_AAC, TRTCAudioFrameFormat_PCM_16KHZ_MONO, TRTCAudioFrameFormat_PCM_8KHZ_MONO };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

