/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.tencent;

public final class TRTCVideoFrameFormat {
  public final static TRTCVideoFrameFormat TRTCVideoFrameFormat_Unknown = new TRTCVideoFrameFormat("TRTCVideoFrameFormat_Unknown", 0);
  public final static TRTCVideoFrameFormat TRTCVideoFrameFormat_YUVI420 = new TRTCVideoFrameFormat("TRTCVideoFrameFormat_YUVI420", 1);
  public final static TRTCVideoFrameFormat TRTCVideoFrameFormat_H264 = new TRTCVideoFrameFormat("TRTCVideoFrameFormat_H264", 2);

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static TRTCVideoFrameFormat swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + TRTCVideoFrameFormat.class + " with value " + swigValue);
  }

  private TRTCVideoFrameFormat(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private TRTCVideoFrameFormat(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private TRTCVideoFrameFormat(String swigName, TRTCVideoFrameFormat swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static TRTCVideoFrameFormat[] swigValues = { TRTCVideoFrameFormat_Unknown, TRTCVideoFrameFormat_YUVI420, TRTCVideoFrameFormat_H264 };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

