/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.tencent;

public class trtcenginewarper {
  public static ITRTCCloud createInstance(long sdkappid) {
    long cPtr = trtcenginewarperJNI.createInstance(sdkappid);
    return (cPtr == 0) ? null : new ITRTCCloud(cPtr, false);
  }

  public static void destroyInstance(ITRTCCloud instance) {
    trtcenginewarperJNI.destroyInstance(ITRTCCloud.getCPtr(instance), instance);
  }

  public static boolean getSDKVersion(String version, SWIGTYPE_p_int length) {
    return trtcenginewarperJNI.getSDKVersion(version, SWIGTYPE_p_int.getCPtr(length));
  }

  public static void setLogLevel(TRTCLogLevel level) {
    trtcenginewarperJNI.setLogLevel(level.swigValue());
  }

  public static void setConsoleEnabled(boolean enabled) {
    trtcenginewarperJNI.setConsoleEnabled(enabled);
  }

  public static void setLogCompressEnabled(boolean enabled) {
    trtcenginewarperJNI.setLogCompressEnabled(enabled);
  }

  public static void setLogDirPath(String path) {
    trtcenginewarperJNI.setLogDirPath(path);
  }

  public static void setLogCallback(ITRTCLogCallback callback) {
    trtcenginewarperJNI.setLogCallback(ITRTCLogCallback.getCPtr(callback), callback);
  }

  public static void setIPCParam(String corePath, String rootDir) {
    trtcenginewarperJNI.setIPCParam(corePath, rootDir);
  }

  public static void setSocks5Proxy(String ip, int port, String user_name, String pass_word) {
    trtcenginewarperJNI.setSocks5Proxy(ip, port, user_name, pass_word);
  }

  public static void setEnvironment(int environment) {
    trtcenginewarperJNI.setEnvironment(environment);
  }

  public static void setConfigPath(String path) {
    trtcenginewarperJNI.setConfigPath(path);
  }

  public static ITRTCMediaMixer createMediaMixer() {
    long cPtr = trtcenginewarperJNI.createMediaMixer();
    return (cPtr == 0) ? null : new ITRTCMediaMixer(cPtr, false);
  }

  public static void destroyMediaMixer(ITRTCMediaMixer instance) {
    trtcenginewarperJNI.destroyMediaMixer(ITRTCMediaMixer.getCPtr(instance), instance);
  }

  public static ITRTCMediaRecorder createMediaRecorder() {
    long cPtr = trtcenginewarperJNI.createMediaRecorder();
    return (cPtr == 0) ? null : new ITRTCMediaRecorder(cPtr, false);
  }

  public static void destroyMediaRecorder(ITRTCMediaRecorder instance) {
    trtcenginewarperJNI.destroyMediaRecorder(ITRTCMediaRecorder.getCPtr(instance), instance);
  }

  public static ITRTCMediaPusher CreateMediaPusher() {
    long cPtr = trtcenginewarperJNI.CreateMediaPusher();
    return (cPtr == 0) ? null : new ITRTCMediaPusher(cPtr, false);
  }

  public static void DestroyMediaPusher(ITRTCMediaPusher instance) {
    trtcenginewarperJNI.DestroyMediaPusher(ITRTCMediaPusher.getCPtr(instance), instance);
  }

  public static ITRTCImage CreateImage() {
    long cPtr = trtcenginewarperJNI.CreateImage();
    return (cPtr == 0) ? null : new ITRTCImage(cPtr, false);
  }

  public static void DestroyImage(ITRTCImage instance) {
    trtcenginewarperJNI.DestroyImage(ITRTCImage.getCPtr(instance), instance);
  }

}
