/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.tencent;

public final class TRTCClientRole {
  public final static TRTCClientRole TRTCClientRole_Anchor = new TRTCClientRole("TRTCClientRole_Anchor", 20);
  public final static TRTCClientRole TRTCClientRole_Audience = new TRTCClientRole("TRTCClientRole_Audience", 21);

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static TRTCClientRole swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + TRTCClientRole.class + " with value " + swigValue);
  }

  private TRTCClientRole(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private TRTCClientRole(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private TRTCClientRole(String swigName, TRTCClientRole swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static TRTCClientRole[] swigValues = { TRTCClientRole_Anchor, TRTCClientRole_Audience };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

