/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.tencent;

public class trtcenginewarperJNI {
  public final static native long createInstance(long jarg1);
  public final static native void destroyInstance(long jarg1, ITRTCCloud jarg1_);
  public final static native boolean getSDKVersion(String jarg1, long jarg2);
  public final static native void setLogLevel(int jarg1);
  public final static native void setConsoleEnabled(boolean jarg1);
  public final static native void setLogCompressEnabled(boolean jarg1);
  public final static native void setLogDirPath(String jarg1);
  public final static native void setLogCallback(long jarg1, ITRTCLogCallback jarg1_);
  public final static native void setIPCParam(String jarg1, String jarg2);
  public final static native void setSocks5Proxy(String jarg1, int jarg2, String jarg3, String jarg4);
  public final static native void setEnvironment(int jarg1);
  public final static native void setConfigPath(String jarg1);
  public final static native void delete_ITRTCCloud(long jarg1);
  public final static native void ITRTCCloud_setCallback(long jarg1, ITRTCCloud jarg1_, long jarg2, ITRTCCloudCallback jarg2_);
  public final static native void ITRTCCloud_enterRoom(long jarg1, ITRTCCloud jarg1_, long jarg2, TRTCParams jarg2_, int jarg3);
  public final static native void ITRTCCloud_exitRoom(long jarg1, ITRTCCloud jarg1_);
  public final static native void ITRTCCloud_setVideoEncoderParam(long jarg1, ITRTCCloud jarg1_, long jarg2, TRTCVideoEncParam jarg2_);
  public final static native int ITRTCCloud_setRemoteVideoRecvCallback(long jarg1, ITRTCCloud jarg1_, String jarg2, int jarg3, long jarg4, ITRTCVideoRecvCallback jarg4_);
  public final static native int ITRTCCloud_setRemoteAudioRecvCallback(long jarg1, ITRTCCloud jarg1_, String jarg2, int jarg3, long jarg4, ITRTCAudioRecvCallback jarg4_);
  public final static native int ITRTCCloud_setRemoteSmallStreamRecvCallback(long jarg1, ITRTCCloud jarg1_, String jarg2, int jarg3, long jarg4, ITRTCVideoRecvCallback jarg4_);
  public final static native int ITRTCCloud_setRemoteSubStreamRecvCallback(long jarg1, ITRTCCloud jarg1_, String jarg2, int jarg3, long jarg4, ITRTCVideoRecvCallback jarg4_);
  public final static native int ITRTCCloud_sendCustomVideoData(long jarg1, ITRTCCloud jarg1_, long jarg2, TRTCVideoFrame jarg2_);
  public final static native int ITRTCCloud_sendCustomAudioData(long jarg1, ITRTCCloud jarg1_, long jarg2, TRTCAudioFrame jarg2_);
  public final static native boolean ITRTCCloud_sendSEIMsg(long jarg1, ITRTCCloud jarg1_, long jarg2, int jarg3, int jarg4);
  public final static native boolean ITRTCCloud_sendCustomCmdMsg(long jarg1, ITRTCCloud jarg1_, long jarg2, long jarg3, int jarg4, boolean jarg5, boolean jarg6);
  public final static native void ITRTCCloud_setAuxVideoEncoderParam(long jarg1, ITRTCCloud jarg1_, long jarg2, TRTCVideoEncParam jarg2_);
  public final static native int ITRTCCloud_sendAuxVideoData(long jarg1, ITRTCCloud jarg1_, long jarg2, TRTCVideoFrame jarg2_);
  public final static native void ITRTCCloud_setEncryptionCallback(long jarg1, ITRTCCloud jarg1_, long jarg2, ITRTCEncryptionCallback jarg2_);
  public final static native void ITRTCCloud_setDecryptionCallback(long jarg1, ITRTCCloud jarg1_, long jarg2, ITRTCDecryptionCallback jarg2_);
  public final static native void delete_ITRTCCloudCallback(long jarg1);
  public final static native void ITRTCCloudCallback_onError(long jarg1, ITRTCCloudCallback jarg1_, int jarg2, String jarg3, long jarg4);
  public final static native void ITRTCCloudCallback_onWarning(long jarg1, ITRTCCloudCallback jarg1_, int jarg2, String jarg3, long jarg4);
  public final static native void ITRTCCloudCallback_onEnterRoom(long jarg1, ITRTCCloudCallback jarg1_, java.math.BigInteger jarg2);
  public final static native void ITRTCCloudCallback_onExitRoom(long jarg1, ITRTCCloudCallback jarg1_, int jarg2);
  public final static native void ITRTCCloudCallback_onUserEnter(long jarg1, ITRTCCloudCallback jarg1_, String jarg2);
  public final static native void ITRTCCloudCallback_onUserExit(long jarg1, ITRTCCloudCallback jarg1_, String jarg2, int jarg3);
  public final static native void ITRTCCloudCallback_onFirstVideoFrame(long jarg1, ITRTCCloudCallback jarg1_, String jarg2, long jarg3, long jarg4);
  public final static native void ITRTCCloudCallback_onFirstVideoFrameSwigExplicitITRTCCloudCallback(long jarg1, ITRTCCloudCallback jarg1_, String jarg2, long jarg3, long jarg4);
  public final static native void ITRTCCloudCallback_onFirstAudioFrame(long jarg1, ITRTCCloudCallback jarg1_, String jarg2);
  public final static native void ITRTCCloudCallback_onFirstAudioFrameSwigExplicitITRTCCloudCallback(long jarg1, ITRTCCloudCallback jarg1_, String jarg2);
  public final static native void ITRTCCloudCallback_onFirstSubStreamFrame(long jarg1, ITRTCCloudCallback jarg1_, String jarg2, long jarg3, long jarg4);
  public final static native void ITRTCCloudCallback_onFirstSubStreamFrameSwigExplicitITRTCCloudCallback(long jarg1, ITRTCCloudCallback jarg1_, String jarg2, long jarg3, long jarg4);
  public final static native void ITRTCCloudCallback_onUserVideoAvailable(long jarg1, ITRTCCloudCallback jarg1_, String jarg2, boolean jarg3);
  public final static native void ITRTCCloudCallback_onUserVideoAvailableSwigExplicitITRTCCloudCallback(long jarg1, ITRTCCloudCallback jarg1_, String jarg2, boolean jarg3);
  public final static native void ITRTCCloudCallback_onUserAudioAvailable(long jarg1, ITRTCCloudCallback jarg1_, String jarg2, boolean jarg3);
  public final static native void ITRTCCloudCallback_onUserAudioAvailableSwigExplicitITRTCCloudCallback(long jarg1, ITRTCCloudCallback jarg1_, String jarg2, boolean jarg3);
  public final static native void ITRTCCloudCallback_onUserSubStreamAvailable(long jarg1, ITRTCCloudCallback jarg1_, String jarg2, boolean jarg3);
  public final static native void ITRTCCloudCallback_onUserSubStreamAvailableSwigExplicitITRTCCloudCallback(long jarg1, ITRTCCloudCallback jarg1_, String jarg2, boolean jarg3);
  public final static native void ITRTCCloudCallback_onRecvSEIMsg(long jarg1, ITRTCCloudCallback jarg1_, String jarg2, long jarg3, int jarg4);
  public final static native void ITRTCCloudCallback_onRecvSEIMsgSwigExplicitITRTCCloudCallback(long jarg1, ITRTCCloudCallback jarg1_, String jarg2, long jarg3, int jarg4);
  public final static native void ITRTCCloudCallback_onRecvCustomCmdMsg(long jarg1, ITRTCCloudCallback jarg1_, String jarg2, int jarg3, int jarg4, long jarg5, int jarg6);
  public final static native void ITRTCCloudCallback_onRecvCustomCmdMsgSwigExplicitITRTCCloudCallback(long jarg1, ITRTCCloudCallback jarg1_, String jarg2, int jarg3, int jarg4, long jarg5, int jarg6);
  public final static native void ITRTCCloudCallback_onMissCustomCmdMsg(long jarg1, ITRTCCloudCallback jarg1_, String jarg2, int jarg3, int jarg4, int jarg5);
  public final static native void ITRTCCloudCallback_onMissCustomCmdMsgSwigExplicitITRTCCloudCallback(long jarg1, ITRTCCloudCallback jarg1_, String jarg2, int jarg3, int jarg4, int jarg5);
  public final static native void ITRTCCloudCallback_onConnectionLost(long jarg1, ITRTCCloudCallback jarg1_);
  public final static native void ITRTCCloudCallback_onConnectionLostSwigExplicitITRTCCloudCallback(long jarg1, ITRTCCloudCallback jarg1_);
  public final static native void ITRTCCloudCallback_onTryToReconnect(long jarg1, ITRTCCloudCallback jarg1_);
  public final static native void ITRTCCloudCallback_onTryToReconnectSwigExplicitITRTCCloudCallback(long jarg1, ITRTCCloudCallback jarg1_);
  public final static native void ITRTCCloudCallback_onConnectionRecovery(long jarg1, ITRTCCloudCallback jarg1_);
  public final static native void ITRTCCloudCallback_onConnectionRecoverySwigExplicitITRTCCloudCallback(long jarg1, ITRTCCloudCallback jarg1_);
  public final static native long new_ITRTCCloudCallback();
  public final static native void ITRTCCloudCallback_director_connect(ITRTCCloudCallback obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void ITRTCCloudCallback_change_ownership(ITRTCCloudCallback obj, long cptr, boolean take_or_release);
  public final static native void delete_ITRTCVideoRecvCallback(long jarg1);
  public final static native void ITRTCVideoRecvCallback_onRecvVideoFrame(long jarg1, ITRTCVideoRecvCallback jarg1_, String jarg2, int jarg3, long jarg4, TRTCVideoFrame jarg4_);
  public final static native void ITRTCVideoRecvCallback_onRecvVideoFrameSwigExplicitITRTCVideoRecvCallback(long jarg1, ITRTCVideoRecvCallback jarg1_, String jarg2, int jarg3, long jarg4, TRTCVideoFrame jarg4_);
  public final static native long new_ITRTCVideoRecvCallback();
  public final static native void ITRTCVideoRecvCallback_director_connect(ITRTCVideoRecvCallback obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void ITRTCVideoRecvCallback_change_ownership(ITRTCVideoRecvCallback obj, long cptr, boolean take_or_release);
  public final static native void delete_ITRTCAudioRecvCallback(long jarg1);
  public final static native void ITRTCAudioRecvCallback_onRecvAudioFrame(long jarg1, ITRTCAudioRecvCallback jarg1_, String jarg2, long jarg3, TRTCAudioFrame jarg3_);
  public final static native void ITRTCAudioRecvCallback_onRecvAudioFrameSwigExplicitITRTCAudioRecvCallback(long jarg1, ITRTCAudioRecvCallback jarg1_, String jarg2, long jarg3, TRTCAudioFrame jarg3_);
  public final static native long new_ITRTCAudioRecvCallback();
  public final static native void ITRTCAudioRecvCallback_director_connect(ITRTCAudioRecvCallback obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void ITRTCAudioRecvCallback_change_ownership(ITRTCAudioRecvCallback obj, long cptr, boolean take_or_release);
  public final static native void delete_ITRTCLogCallback(long jarg1);
  public final static native void ITRTCLogCallback_onLog(long jarg1, ITRTCLogCallback jarg1_, String jarg2, int jarg3, String jarg4);
  public final static native void ITRTCLogCallback_onLogSwigExplicitITRTCLogCallback(long jarg1, ITRTCLogCallback jarg1_, String jarg2, int jarg3, String jarg4);
  public final static native long new_ITRTCLogCallback();
  public final static native void ITRTCLogCallback_director_connect(ITRTCLogCallback obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void ITRTCLogCallback_change_ownership(ITRTCLogCallback obj, long cptr, boolean take_or_release);
  public final static native void delete_ITRTCEncryptionCallback(long jarg1);
  public final static native boolean ITRTCEncryptionCallback_onAudioFrameEncrypt(long jarg1, ITRTCEncryptionCallback jarg1_, long jarg2, TRTCCustomEncryptionData jarg2_);
  public final static native boolean ITRTCEncryptionCallback_onAudioFrameEncryptSwigExplicitITRTCEncryptionCallback(long jarg1, ITRTCEncryptionCallback jarg1_, long jarg2, TRTCCustomEncryptionData jarg2_);
  public final static native boolean ITRTCEncryptionCallback_onVideoFrameEncrypt(long jarg1, ITRTCEncryptionCallback jarg1_, int jarg2, long jarg3, TRTCCustomEncryptionData jarg3_);
  public final static native boolean ITRTCEncryptionCallback_onVideoFrameEncryptSwigExplicitITRTCEncryptionCallback(long jarg1, ITRTCEncryptionCallback jarg1_, int jarg2, long jarg3, TRTCCustomEncryptionData jarg3_);
  public final static native long new_ITRTCEncryptionCallback();
  public final static native void ITRTCEncryptionCallback_director_connect(ITRTCEncryptionCallback obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void ITRTCEncryptionCallback_change_ownership(ITRTCEncryptionCallback obj, long cptr, boolean take_or_release);
  public final static native void delete_ITRTCDecryptionCallback(long jarg1);
  public final static native boolean ITRTCDecryptionCallback_onAudioFrameDecrypt(long jarg1, ITRTCDecryptionCallback jarg1_, String jarg2, long jarg3, TRTCCustomEncryptionData jarg3_);
  public final static native boolean ITRTCDecryptionCallback_onAudioFrameDecryptSwigExplicitITRTCDecryptionCallback(long jarg1, ITRTCDecryptionCallback jarg1_, String jarg2, long jarg3, TRTCCustomEncryptionData jarg3_);
  public final static native boolean ITRTCDecryptionCallback_onVideoFrameDecrypt(long jarg1, ITRTCDecryptionCallback jarg1_, String jarg2, int jarg3, long jarg4, TRTCCustomEncryptionData jarg4_);
  public final static native boolean ITRTCDecryptionCallback_onVideoFrameDecryptSwigExplicitITRTCDecryptionCallback(long jarg1, ITRTCDecryptionCallback jarg1_, String jarg2, int jarg3, long jarg4, TRTCCustomEncryptionData jarg4_);
  public final static native long new_ITRTCDecryptionCallback();
  public final static native void ITRTCDecryptionCallback_director_connect(ITRTCDecryptionCallback obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void ITRTCDecryptionCallback_change_ownership(ITRTCDecryptionCallback obj, long cptr, boolean take_or_release);
  public final static native void Region_offset_x_set(long jarg1, Region jarg1_, int jarg2);
  public final static native int Region_offset_x_get(long jarg1, Region jarg1_);
  public final static native void Region_offset_y_set(long jarg1, Region jarg1_, int jarg2);
  public final static native int Region_offset_y_get(long jarg1, Region jarg1_);
  public final static native void Region_width_set(long jarg1, Region jarg1_, int jarg2);
  public final static native int Region_width_get(long jarg1, Region jarg1_);
  public final static native void Region_height_set(long jarg1, Region jarg1_, int jarg2);
  public final static native int Region_height_get(long jarg1, Region jarg1_);
  public final static native void Region_bgcolor_set(long jarg1, Region jarg1_, int jarg2);
  public final static native int Region_bgcolor_get(long jarg1, Region jarg1_);
  public final static native void Region_option_set(long jarg1, Region jarg1_, int jarg2);
  public final static native int Region_option_get(long jarg1, Region jarg1_);
  public final static native void Region_zOrder_set(long jarg1, Region jarg1_, int jarg2);
  public final static native int Region_zOrder_get(long jarg1, Region jarg1_);
  public final static native long new_Region__SWIG_0();
  public final static native long new_Region__SWIG_1(long jarg1, Region jarg1_);
  public final static native long new_Region__SWIG_2(int jarg1, int jarg2, int jarg3, int jarg4, int jarg5, int jarg6, int jarg7);
  public final static native void delete_Region(long jarg1);
  public final static native long createMediaMixer();
  public final static native void destroyMediaMixer(long jarg1, ITRTCMediaMixer jarg1_);
  public final static native void delete_ITRTCMediaMixerCallback(long jarg1);
  public final static native void ITRTCMediaMixerCallback_onMixedAudioFrame(long jarg1, ITRTCMediaMixerCallback jarg1_, long jarg2, TRTCAudioFrame jarg2_);
  public final static native void ITRTCMediaMixerCallback_onMixedVideoFrame(long jarg1, ITRTCMediaMixerCallback jarg1_, long jarg2, TRTCVideoFrame jarg2_);
  public final static native void ITRTCMediaMixerCallback_onError(long jarg1, ITRTCMediaMixerCallback jarg1_, int jarg2, String jarg3);
  public final static native long new_ITRTCMediaMixerCallback();
  public final static native void ITRTCMediaMixerCallback_director_connect(ITRTCMediaMixerCallback obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void ITRTCMediaMixerCallback_change_ownership(ITRTCMediaMixerCallback obj, long cptr, boolean take_or_release);
  public final static native void delete_ITRTCMediaMixer(long jarg1);
  public final static native void ITRTCMediaMixer_setCallback(long jarg1, ITRTCMediaMixer jarg1_, long jarg2, ITRTCMediaMixerCallback jarg2_);
  public final static native int ITRTCMediaMixer_setCanvas(long jarg1, ITRTCMediaMixer jarg1_, int jarg2, int jarg3, int jarg4, int jarg5);
  public final static native int ITRTCMediaMixer_start(long jarg1, ITRTCMediaMixer jarg1_, boolean jarg2, boolean jarg3);
  public final static native int ITRTCMediaMixer_stop(long jarg1, ITRTCMediaMixer jarg1_);
  public final static native int ITRTCMediaMixer_clearRegions(long jarg1, ITRTCMediaMixer jarg1_);
  public final static native int ITRTCMediaMixer_setRegion(long jarg1, ITRTCMediaMixer jarg1_, String jarg2, long jarg3, Region jarg3_);
  public final static native int ITRTCMediaMixer_applyRegions(long jarg1, ITRTCMediaMixer jarg1_);
  public final static native int ITRTCMediaMixer_addAudioFrame(long jarg1, ITRTCMediaMixer jarg1_, String jarg2, long jarg3, TRTCAudioFrame jarg3_);
  public final static native int ITRTCMediaMixer_addVideoFrame(long jarg1, ITRTCMediaMixer jarg1_, String jarg2, long jarg3, TRTCVideoFrame jarg3_);
  public final static native long createMediaRecorder();
  public final static native void destroyMediaRecorder(long jarg1, ITRTCMediaRecorder jarg1_);
  public final static native void delete_ITRTCMediaRecorderCallback(long jarg1);
  public final static native void ITRTCMediaRecorderCallback_onFinished(long jarg1, ITRTCMediaRecorderCallback jarg1_, String jarg2, int jarg3, String jarg4);
  public final static native void ITRTCMediaRecorderCallback_onFinishedSwigExplicitITRTCMediaRecorderCallback(long jarg1, ITRTCMediaRecorderCallback jarg1_, String jarg2, int jarg3, String jarg4);
  public final static native long new_ITRTCMediaRecorderCallback();
  public final static native void ITRTCMediaRecorderCallback_director_connect(ITRTCMediaRecorderCallback obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void ITRTCMediaRecorderCallback_change_ownership(ITRTCMediaRecorderCallback obj, long cptr, boolean take_or_release);
  public final static native void delete_ITRTCMediaRecorder(long jarg1);
  public final static native void ITRTCMediaRecorder_setCallback(long jarg1, ITRTCMediaRecorder jarg1_, long jarg2, ITRTCMediaRecorderCallback jarg2_);
  public final static native boolean ITRTCMediaRecorder_setParam(long jarg1, ITRTCMediaRecorder jarg1_, long jarg2, String jarg3, String jarg4, int jarg5, String jarg6);
  public final static native void ITRTCMediaRecorder_addAudioFrame(long jarg1, ITRTCMediaRecorder jarg1_, String jarg2, long jarg3, TRTCAudioFrame jarg3_);
  public final static native void ITRTCMediaRecorder_addVideoFrame(long jarg1, ITRTCMediaRecorder jarg1_, String jarg2, int jarg3, long jarg4, TRTCVideoFrame jarg4_);
  public final static native void ITRTCMediaRecorder_stopOne(long jarg1, ITRTCMediaRecorder jarg1_, String jarg2);
  public final static native void ITRTCMediaRecorder_stopAll(long jarg1, ITRTCMediaRecorder jarg1_);
  public final static native void TRTCVideoFrame_videoFormat_set(long jarg1, TRTCVideoFrame jarg1_, int jarg2);
  public final static native int TRTCVideoFrame_videoFormat_get(long jarg1, TRTCVideoFrame jarg1_);
  public final static native void TRTCVideoFrame_bufferType_set(long jarg1, TRTCVideoFrame jarg1_, int jarg2);
  public final static native int TRTCVideoFrame_bufferType_get(long jarg1, TRTCVideoFrame jarg1_);
  public final static native void TRTCVideoFrame_data_set(long jarg1, TRTCVideoFrame jarg1_, byte[] jarg2);
  public final static native byte[] TRTCVideoFrame_data_get(long jarg1, TRTCVideoFrame jarg1_);
  public final static native void TRTCVideoFrame_textureId_set(long jarg1, TRTCVideoFrame jarg1_, int jarg2);
  public final static native int TRTCVideoFrame_textureId_get(long jarg1, TRTCVideoFrame jarg1_);
  public final static native void TRTCVideoFrame_length_set(long jarg1, TRTCVideoFrame jarg1_, long jarg2);
  public final static native long TRTCVideoFrame_length_get(long jarg1, TRTCVideoFrame jarg1_);
  public final static native void TRTCVideoFrame_width_set(long jarg1, TRTCVideoFrame jarg1_, long jarg2);
  public final static native long TRTCVideoFrame_width_get(long jarg1, TRTCVideoFrame jarg1_);
  public final static native void TRTCVideoFrame_height_set(long jarg1, TRTCVideoFrame jarg1_, long jarg2);
  public final static native long TRTCVideoFrame_height_get(long jarg1, TRTCVideoFrame jarg1_);
  public final static native void TRTCVideoFrame_timestamp_set(long jarg1, TRTCVideoFrame jarg1_, java.math.BigInteger jarg2);
  public final static native java.math.BigInteger TRTCVideoFrame_timestamp_get(long jarg1, TRTCVideoFrame jarg1_);
  public final static native void TRTCVideoFrame_rotation_set(long jarg1, TRTCVideoFrame jarg1_, int jarg2);
  public final static native int TRTCVideoFrame_rotation_get(long jarg1, TRTCVideoFrame jarg1_);
  public final static native long new_TRTCVideoFrame();
  public final static native void TRTCVideoFrame_initData(long jarg1, TRTCVideoFrame jarg1_, int jarg2);
  public final static native void TRTCVideoFrame_uninitData(long jarg1, TRTCVideoFrame jarg1_, int jarg2);
  public final static native void delete_TRTCVideoFrame(long jarg1);
  public final static native void TRTCAudioFrame_audioFormat_set(long jarg1, TRTCAudioFrame jarg1_, int jarg2);
  public final static native int TRTCAudioFrame_audioFormat_get(long jarg1, TRTCAudioFrame jarg1_);
  public final static native void TRTCAudioFrame_data_set(long jarg1, TRTCAudioFrame jarg1_, byte[] jarg2);
  public final static native byte[] TRTCAudioFrame_data_get(long jarg1, TRTCAudioFrame jarg1_);
  public final static native void TRTCAudioFrame_length_set(long jarg1, TRTCAudioFrame jarg1_, long jarg2);
  public final static native long TRTCAudioFrame_length_get(long jarg1, TRTCAudioFrame jarg1_);
  public final static native void TRTCAudioFrame_sampleRate_set(long jarg1, TRTCAudioFrame jarg1_, long jarg2);
  public final static native long TRTCAudioFrame_sampleRate_get(long jarg1, TRTCAudioFrame jarg1_);
  public final static native void TRTCAudioFrame_channel_set(long jarg1, TRTCAudioFrame jarg1_, long jarg2);
  public final static native long TRTCAudioFrame_channel_get(long jarg1, TRTCAudioFrame jarg1_);
  public final static native void TRTCAudioFrame_timestamp_set(long jarg1, TRTCAudioFrame jarg1_, java.math.BigInteger jarg2);
  public final static native java.math.BigInteger TRTCAudioFrame_timestamp_get(long jarg1, TRTCAudioFrame jarg1_);
  public final static native long new_TRTCAudioFrame();
  public final static native void TRTCAudioFrame_initData(long jarg1, TRTCAudioFrame jarg1_, int jarg2);
  public final static native void TRTCAudioFrame_uninitData(long jarg1, TRTCAudioFrame jarg1_, int jarg2);
  public final static native void delete_TRTCAudioFrame(long jarg1);
  public final static native void StringBuffer_buffer_set(long jarg1, StringBuffer jarg1_, String jarg2);
  public final static native String StringBuffer_buffer_get(long jarg1, StringBuffer jarg1_);
  public final static native void StringBuffer_buffer_len_set(long jarg1, StringBuffer jarg1_, long jarg2);
  public final static native long StringBuffer_buffer_len_get(long jarg1, StringBuffer jarg1_);
  public final static native long new_StringBuffer();
  public final static native void delete_StringBuffer(long jarg1);
  public final static native void TRTCParams_sdkAppId_set(long jarg1, TRTCParams jarg1_, long jarg2);
  public final static native long TRTCParams_sdkAppId_get(long jarg1, TRTCParams jarg1_);
  public final static native void TRTCParams_roomId_set(long jarg1, TRTCParams jarg1_, long jarg2);
  public final static native long TRTCParams_roomId_get(long jarg1, TRTCParams jarg1_);
  public final static native void TRTCParams_userId_set(long jarg1, TRTCParams jarg1_, long jarg2, StringBuffer jarg2_);
  public final static native long TRTCParams_userId_get(long jarg1, TRTCParams jarg1_);
  public final static native void TRTCParams_userSig_set(long jarg1, TRTCParams jarg1_, long jarg2, StringBuffer jarg2_);
  public final static native long TRTCParams_userSig_get(long jarg1, TRTCParams jarg1_);
  public final static native void TRTCParams_privateMapKey_set(long jarg1, TRTCParams jarg1_, long jarg2, StringBuffer jarg2_);
  public final static native long TRTCParams_privateMapKey_get(long jarg1, TRTCParams jarg1_);
  public final static native void TRTCParams_businessInfo_set(long jarg1, TRTCParams jarg1_, long jarg2, StringBuffer jarg2_);
  public final static native long TRTCParams_businessInfo_get(long jarg1, TRTCParams jarg1_);
  public final static native void TRTCParams_clientRole_set(long jarg1, TRTCParams jarg1_, int jarg2);
  public final static native int TRTCParams_clientRole_get(long jarg1, TRTCParams jarg1_);
  public final static native long new_TRTCParams();
  public final static native void delete_TRTCParams(long jarg1);
  public final static native void TRTCVideoEncParam_videoResolution_set(long jarg1, TRTCVideoEncParam jarg1_, int jarg2);
  public final static native int TRTCVideoEncParam_videoResolution_get(long jarg1, TRTCVideoEncParam jarg1_);
  public final static native void TRTCVideoEncParam_resMode_set(long jarg1, TRTCVideoEncParam jarg1_, int jarg2);
  public final static native int TRTCVideoEncParam_resMode_get(long jarg1, TRTCVideoEncParam jarg1_);
  public final static native void TRTCVideoEncParam_encType_set(long jarg1, TRTCVideoEncParam jarg1_, int jarg2);
  public final static native int TRTCVideoEncParam_encType_get(long jarg1, TRTCVideoEncParam jarg1_);
  public final static native void TRTCVideoEncParam_videoFps_set(long jarg1, TRTCVideoEncParam jarg1_, long jarg2);
  public final static native long TRTCVideoEncParam_videoFps_get(long jarg1, TRTCVideoEncParam jarg1_);
  public final static native void TRTCVideoEncParam_videoBitrate_set(long jarg1, TRTCVideoEncParam jarg1_, long jarg2);
  public final static native long TRTCVideoEncParam_videoBitrate_get(long jarg1, TRTCVideoEncParam jarg1_);
  public final static native long new_TRTCVideoEncParam();
  public final static native void delete_TRTCVideoEncParam(long jarg1);
  public final static native void TRTCCustomEncryptionData_unEncryptedData_set(long jarg1, TRTCCustomEncryptionData jarg1_, byte[] jarg2);
  public final static native byte[] TRTCCustomEncryptionData_unEncryptedData_get(long jarg1, TRTCCustomEncryptionData jarg1_);
  public final static native void TRTCCustomEncryptionData_unEncryptedDataLength_set(long jarg1, TRTCCustomEncryptionData jarg1_, long jarg2);
  public final static native long TRTCCustomEncryptionData_unEncryptedDataLength_get(long jarg1, TRTCCustomEncryptionData jarg1_);
  public final static native void TRTCCustomEncryptionData_EncryptedData_set(long jarg1, TRTCCustomEncryptionData jarg1_, byte[] jarg2);
  public final static native byte[] TRTCCustomEncryptionData_EncryptedData_get(long jarg1, TRTCCustomEncryptionData jarg1_);
  public final static native void TRTCCustomEncryptionData_EncryptedDataLength_set(long jarg1, TRTCCustomEncryptionData jarg1_, long jarg2);
  public final static native long TRTCCustomEncryptionData_EncryptedDataLength_get(long jarg1, TRTCCustomEncryptionData jarg1_);
  public final static native long new_TRTCCustomEncryptionData();
  public final static native void TRTCCustomEncryptionData_is_encryption_buffer_setted_set(long jarg1, TRTCCustomEncryptionData jarg1_, boolean jarg2);
  public final static native boolean TRTCCustomEncryptionData_is_encryption_buffer_setted_get(long jarg1, TRTCCustomEncryptionData jarg1_);
  public final static native void TRTCCustomEncryptionData_is_decryption_buffer_setted_set(long jarg1, TRTCCustomEncryptionData jarg1_, boolean jarg2);
  public final static native boolean TRTCCustomEncryptionData_is_decryption_buffer_setted_get(long jarg1, TRTCCustomEncryptionData jarg1_);
  public final static native void delete_TRTCCustomEncryptionData(long jarg1);
  public final static native void TRTCCustomEncryptionData_initEncryptionData(long jarg1, TRTCCustomEncryptionData jarg1_, int jarg2);
  public final static native void TRTCCustomEncryptionData_initUnEncryptionData(long jarg1, TRTCCustomEncryptionData jarg1_, int jarg2);
  public final static native void PushConfig_room_param_set(long jarg1, PushConfig jarg1_, long jarg2, TRTCParams jarg2_);
  public final static native long PushConfig_room_param_get(long jarg1, PushConfig jarg1_);
  public final static native void PushConfig_push_content_set(long jarg1, PushConfig jarg1_, int jarg2);
  public final static native int PushConfig_push_content_get(long jarg1, PushConfig jarg1_);
  public final static native void PushConfig_raw_h264_set(long jarg1, PushConfig jarg1_, boolean jarg2);
  public final static native boolean PushConfig_raw_h264_get(long jarg1, PushConfig jarg1_);
  public final static native void PushConfig_sence_set(long jarg1, PushConfig jarg1_, int jarg2);
  public final static native int PushConfig_sence_get(long jarg1, PushConfig jarg1_);
  public final static native void PushConfig_is_repeat_last_pic_when_pausing_set(long jarg1, PushConfig jarg1_, boolean jarg2);
  public final static native boolean PushConfig_is_repeat_last_pic_when_pausing_get(long jarg1, PushConfig jarg1_);
  public final static native void PushConfig_audio_channels_set(long jarg1, PushConfig jarg1_, int jarg2);
  public final static native int PushConfig_audio_channels_get(long jarg1, PushConfig jarg1_);
  public final static native long new_PushConfig();
  public final static native void delete_PushConfig(long jarg1);
  public final static native long CreateMediaPusher();
  public final static native void DestroyMediaPusher(long jarg1, ITRTCMediaPusher jarg1_);
  public final static native void delete_ITRTCMediaPusherCallback(long jarg1);
  public final static native void ITRTCMediaPusherCallback_OnPushError(long jarg1, ITRTCMediaPusherCallback jarg1_, int jarg2, String jarg3);
  public final static native void ITRTCMediaPusherCallback_OnPushBegin(long jarg1, ITRTCMediaPusherCallback jarg1_, String jarg2);
  public final static native void ITRTCMediaPusherCallback_OnPushBeginSwigExplicitITRTCMediaPusherCallback(long jarg1, ITRTCMediaPusherCallback jarg1_, String jarg2);
  public final static native void ITRTCMediaPusherCallback_OnPushEnd(long jarg1, ITRTCMediaPusherCallback jarg1_, String jarg2);
  public final static native void ITRTCMediaPusherCallback_OnPushEndSwigExplicitITRTCMediaPusherCallback(long jarg1, ITRTCMediaPusherCallback jarg1_, String jarg2);
  public final static native void ITRTCMediaPusherCallback_OnPushProgress(long jarg1, ITRTCMediaPusherCallback jarg1_, String jarg2, int jarg3, int jarg4);
  public final static native void ITRTCMediaPusherCallback_OnPushProgressSwigExplicitITRTCMediaPusherCallback(long jarg1, ITRTCMediaPusherCallback jarg1_, String jarg2, int jarg3, int jarg4);
  public final static native long new_ITRTCMediaPusherCallback();
  public final static native void ITRTCMediaPusherCallback_director_connect(ITRTCMediaPusherCallback obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void ITRTCMediaPusherCallback_change_ownership(ITRTCMediaPusherCallback obj, long cptr, boolean take_or_release);
  public final static native void delete_ITRTCMediaPusher(long jarg1);
  public final static native void ITRTCMediaPusher_SetCallback(long jarg1, ITRTCMediaPusher jarg1_, long jarg2, ITRTCMediaPusherCallback jarg2_);
  public final static native void ITRTCMediaPusher_StartWithConfig(long jarg1, ITRTCMediaPusher jarg1_, long jarg2, PushConfig jarg2_);
  public final static native void ITRTCMediaPusher_Stop(long jarg1, ITRTCMediaPusher jarg1_);
  public final static native void ITRTCMediaPusher_PushMedia(long jarg1, ITRTCMediaPusher jarg1_, String jarg2, String jarg3);
  public final static native void ITRTCMediaPusher_SetWatermarkPath(long jarg1, ITRTCMediaPusher jarg1_, String jarg2);
  public final static native void ITRTCMediaPusher_SetWatermarkLocation(long jarg1, ITRTCMediaPusher jarg1_, float jarg2, float jarg3, float jarg4);
  public final static native boolean ITRTCMediaPusher_IsWatermarkValid(long jarg1, ITRTCMediaPusher jarg1_);
  public final static native void ITRTCMediaPusher_Pause(long jarg1, ITRTCMediaPusher jarg1_);
  public final static native void ITRTCMediaPusher_Resume(long jarg1, ITRTCMediaPusher jarg1_);
  public final static native void ITRTCMediaPusher_Seek(long jarg1, ITRTCMediaPusher jarg1_, int jarg2);
  public final static native void delete_ITRTCImageCallback(long jarg1);
  public final static native void ITRTCImageCallback_OnWriteComplete(long jarg1, ITRTCImageCallback jarg1_, String jarg2, int jarg3, boolean jarg4);
  public final static native long new_ITRTCImageCallback();
  public final static native void ITRTCImageCallback_director_connect(ITRTCImageCallback obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void ITRTCImageCallback_change_ownership(ITRTCImageCallback obj, long cptr, boolean take_or_release);
  public final static native void delete_ITRTCImage(long jarg1);
  public final static native void ITRTCImage_SetCallback(long jarg1, ITRTCImage jarg1_, long jarg2, ITRTCImageCallback jarg2_);
  public final static native int ITRTCImage_WriteImage(long jarg1, ITRTCImage jarg1_, long jarg2, TRTCVideoFrame jarg2_, String jarg3, int jarg4);
  public final static native long CreateImage();
  public final static native void DestroyImage(long jarg1, ITRTCImage jarg1_);

  public static void SwigDirector_ITRTCCloudCallback_onError(ITRTCCloudCallback self, int errCode, String errMsg, long arg) {
    self.onError(TXLiteAVError.swigToEnum(errCode), errMsg, (arg == 0) ? null : new SWIGTYPE_p_void(arg, false));
  }
  public static void SwigDirector_ITRTCCloudCallback_onWarning(ITRTCCloudCallback self, int warningCode, String warningMsg, long arg) {
    self.onWarning(TXLiteAVWarning.swigToEnum(warningCode), warningMsg, (arg == 0) ? null : new SWIGTYPE_p_void(arg, false));
  }
  public static void SwigDirector_ITRTCCloudCallback_onEnterRoom(ITRTCCloudCallback self, java.math.BigInteger elapsed) {
    self.onEnterRoom(elapsed);
  }
  public static void SwigDirector_ITRTCCloudCallback_onExitRoom(ITRTCCloudCallback self, int reason) {
    self.onExitRoom(reason);
  }
  public static void SwigDirector_ITRTCCloudCallback_onUserEnter(ITRTCCloudCallback self, String userId) {
    self.onUserEnter(userId);
  }
  public static void SwigDirector_ITRTCCloudCallback_onUserExit(ITRTCCloudCallback self, String userId, int reason) {
    self.onUserExit(userId, reason);
  }
  public static void SwigDirector_ITRTCCloudCallback_onFirstVideoFrame(ITRTCCloudCallback self, String userId, long width, long height) {
    self.onFirstVideoFrame(userId, width, height);
  }
  public static void SwigDirector_ITRTCCloudCallback_onFirstAudioFrame(ITRTCCloudCallback self, String userId) {
    self.onFirstAudioFrame(userId);
  }
  public static void SwigDirector_ITRTCCloudCallback_onFirstSubStreamFrame(ITRTCCloudCallback self, String userId, long width, long height) {
    self.onFirstSubStreamFrame(userId, width, height);
  }
  public static void SwigDirector_ITRTCCloudCallback_onUserVideoAvailable(ITRTCCloudCallback self, String userId, boolean available) {
    self.onUserVideoAvailable(userId, available);
  }
  public static void SwigDirector_ITRTCCloudCallback_onUserAudioAvailable(ITRTCCloudCallback self, String userId, boolean available) {
    self.onUserAudioAvailable(userId, available);
  }
  public static void SwigDirector_ITRTCCloudCallback_onUserSubStreamAvailable(ITRTCCloudCallback self, String userId, boolean available) {
    self.onUserSubStreamAvailable(userId, available);
  }
  public static void SwigDirector_ITRTCCloudCallback_onRecvSEIMsg(ITRTCCloudCallback self, String userId, long data, int datalen) {
    self.onRecvSEIMsg(userId, (data == 0) ? null : new SWIGTYPE_p_unsigned_char(data, false), datalen);
  }
  public static void SwigDirector_ITRTCCloudCallback_onRecvCustomCmdMsg(ITRTCCloudCallback self, String userId, int cmdId, int seq, long msg, int msglen) {
    self.onRecvCustomCmdMsg(userId, cmdId, seq, (msg == 0) ? null : new SWIGTYPE_p_unsigned_char(msg, false), msglen);
  }
  public static void SwigDirector_ITRTCCloudCallback_onMissCustomCmdMsg(ITRTCCloudCallback self, String userId, int cmdId, int errCode, int missed) {
    self.onMissCustomCmdMsg(userId, cmdId, errCode, missed);
  }
  public static void SwigDirector_ITRTCCloudCallback_onConnectionLost(ITRTCCloudCallback self) {
    self.onConnectionLost();
  }
  public static void SwigDirector_ITRTCCloudCallback_onTryToReconnect(ITRTCCloudCallback self) {
    self.onTryToReconnect();
  }
  public static void SwigDirector_ITRTCCloudCallback_onConnectionRecovery(ITRTCCloudCallback self) {
    self.onConnectionRecovery();
  }
  public static void SwigDirector_ITRTCVideoRecvCallback_onRecvVideoFrame(ITRTCVideoRecvCallback self, String userId, int streamType, long frame) {
    self.onRecvVideoFrame(userId, TRTCVideoStreamType.swigToEnum(streamType), (frame == 0) ? null : new TRTCVideoFrame(frame, false));
  }
  public static void SwigDirector_ITRTCAudioRecvCallback_onRecvAudioFrame(ITRTCAudioRecvCallback self, String userId, long frame) {
    self.onRecvAudioFrame(userId, (frame == 0) ? null : new TRTCAudioFrame(frame, false));
  }
  public static void SwigDirector_ITRTCLogCallback_onLog(ITRTCLogCallback self, String log, int level, String module) {
    self.onLog(log, TRTCLogLevel.swigToEnum(level), module);
  }
  public static boolean SwigDirector_ITRTCEncryptionCallback_onAudioFrameEncrypt(ITRTCEncryptionCallback self, long data) {
    return self.onAudioFrameEncrypt((data == 0) ? null : new TRTCCustomEncryptionData(data, false));
  }
  public static boolean SwigDirector_ITRTCEncryptionCallback_onVideoFrameEncrypt(ITRTCEncryptionCallback self, int streamType, long data) {
    return self.onVideoFrameEncrypt(TRTCVideoStreamType.swigToEnum(streamType), (data == 0) ? null : new TRTCCustomEncryptionData(data, false));
  }
  public static boolean SwigDirector_ITRTCDecryptionCallback_onAudioFrameDecrypt(ITRTCDecryptionCallback self, String userId, long data) {
    return self.onAudioFrameDecrypt(userId, (data == 0) ? null : new TRTCCustomEncryptionData(data, false));
  }
  public static boolean SwigDirector_ITRTCDecryptionCallback_onVideoFrameDecrypt(ITRTCDecryptionCallback self, String userId, int streamType, long data) {
    return self.onVideoFrameDecrypt(userId, TRTCVideoStreamType.swigToEnum(streamType), (data == 0) ? null : new TRTCCustomEncryptionData(data, false));
  }
  public static void SwigDirector_ITRTCMediaMixerCallback_onMixedAudioFrame(ITRTCMediaMixerCallback self, long frame) {
    self.onMixedAudioFrame((frame == 0) ? null : new TRTCAudioFrame(frame, false));
  }
  public static void SwigDirector_ITRTCMediaMixerCallback_onMixedVideoFrame(ITRTCMediaMixerCallback self, long frame) {
    self.onMixedVideoFrame((frame == 0) ? null : new TRTCVideoFrame(frame, false));
  }
  public static void SwigDirector_ITRTCMediaMixerCallback_onError(ITRTCMediaMixerCallback self, int errcode, String errmsg) {
    self.onError(errcode, errmsg);
  }
  public static void SwigDirector_ITRTCMediaRecorderCallback_onFinished(ITRTCMediaRecorderCallback self, String userId, int output, String filepath) {
    self.onFinished(userId, output, filepath);
  }
  public static void SwigDirector_ITRTCMediaPusherCallback_OnPushError(ITRTCMediaPusherCallback self, int error_code, String error_message) {
    self.OnPushError(MediaPushError.swigToEnum(error_code), error_message);
  }
  public static void SwigDirector_ITRTCMediaPusherCallback_OnPushBegin(ITRTCMediaPusherCallback self, String file_url) {
    self.OnPushBegin(file_url);
  }
  public static void SwigDirector_ITRTCMediaPusherCallback_OnPushEnd(ITRTCMediaPusherCallback self, String file_url) {
    self.OnPushEnd(file_url);
  }
  public static void SwigDirector_ITRTCMediaPusherCallback_OnPushProgress(ITRTCMediaPusherCallback self, String file_url, int position, int duration) {
    self.OnPushProgress(file_url, position, duration);
  }
  public static void SwigDirector_ITRTCImageCallback_OnWriteComplete(ITRTCImageCallback self, String file_path, int type, boolean is_ok) {
    self.OnWriteComplete(file_path, ImageType.swigToEnum(type), is_ok);
  }

  private final static native void swig_module_init();
  static {
    swig_module_init();
  }
}
