/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.tencent;

public final class TRTCVideoResolution {
  public final static TRTCVideoResolution TRTCVideoResolution_120_120 = new TRTCVideoResolution("TRTCVideoResolution_120_120", 1);
  public final static TRTCVideoResolution TRTCVideoResolution_160_160 = new TRTCVideoResolution("TRTCVideoResolution_160_160", 3);
  public final static TRTCVideoResolution TRTCVideoResolution_270_270 = new TRTCVideoResolution("TRTCVideoResolution_270_270", 5);
  public final static TRTCVideoResolution TRTCVideoResolution_480_480 = new TRTCVideoResolution("TRTCVideoResolution_480_480", 7);
  public final static TRTCVideoResolution TRTCVideoResolution_160_120 = new TRTCVideoResolution("TRTCVideoResolution_160_120", 50);
  public final static TRTCVideoResolution TRTCVideoResolution_240_180 = new TRTCVideoResolution("TRTCVideoResolution_240_180", 52);
  public final static TRTCVideoResolution TRTCVideoResolution_280_210 = new TRTCVideoResolution("TRTCVideoResolution_280_210", 54);
  public final static TRTCVideoResolution TRTCVideoResolution_320_240 = new TRTCVideoResolution("TRTCVideoResolution_320_240", 56);
  public final static TRTCVideoResolution TRTCVideoResolution_400_300 = new TRTCVideoResolution("TRTCVideoResolution_400_300", 58);
  public final static TRTCVideoResolution TRTCVideoResolution_480_360 = new TRTCVideoResolution("TRTCVideoResolution_480_360", 60);
  public final static TRTCVideoResolution TRTCVideoResolution_640_480 = new TRTCVideoResolution("TRTCVideoResolution_640_480", 62);
  public final static TRTCVideoResolution TRTCVideoResolution_960_720 = new TRTCVideoResolution("TRTCVideoResolution_960_720", 64);
  public final static TRTCVideoResolution TRTCVideoResolution_160_90 = new TRTCVideoResolution("TRTCVideoResolution_160_90", 100);
  public final static TRTCVideoResolution TRTCVideoResolution_256_144 = new TRTCVideoResolution("TRTCVideoResolution_256_144", 102);
  public final static TRTCVideoResolution TRTCVideoResolution_320_180 = new TRTCVideoResolution("TRTCVideoResolution_320_180", 104);
  public final static TRTCVideoResolution TRTCVideoResolution_480_270 = new TRTCVideoResolution("TRTCVideoResolution_480_270", 106);
  public final static TRTCVideoResolution TRTCVideoResolution_640_360 = new TRTCVideoResolution("TRTCVideoResolution_640_360", 108);
  public final static TRTCVideoResolution TRTCVideoResolution_960_540 = new TRTCVideoResolution("TRTCVideoResolution_960_540", 110);
  public final static TRTCVideoResolution TRTCVideoResolution_1280_720 = new TRTCVideoResolution("TRTCVideoResolution_1280_720", 112);
  public final static TRTCVideoResolution TRTCVideoResolution_1920_1080 = new TRTCVideoResolution("TRTCVideoResolution_1920_1080", 113);
  public final static TRTCVideoResolution TRTCVideoResolution_640_368 = new TRTCVideoResolution("TRTCVideoResolution_640_368", 208);
  public final static TRTCVideoResolution TRTCVideoResolution_960_544 = new TRTCVideoResolution("TRTCVideoResolution_960_544", 209);

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static TRTCVideoResolution swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + TRTCVideoResolution.class + " with value " + swigValue);
  }

  private TRTCVideoResolution(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private TRTCVideoResolution(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private TRTCVideoResolution(String swigName, TRTCVideoResolution swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static TRTCVideoResolution[] swigValues = { TRTCVideoResolution_120_120, TRTCVideoResolution_160_160, TRTCVideoResolution_270_270, TRTCVideoResolution_480_480, TRTCVideoResolution_160_120, TRTCVideoResolution_240_180, TRTCVideoResolution_280_210, TRTCVideoResolution_320_240, TRTCVideoResolution_400_300, TRTCVideoResolution_480_360, TRTCVideoResolution_640_480, TRTCVideoResolution_960_720, TRTCVideoResolution_160_90, TRTCVideoResolution_256_144, TRTCVideoResolution_320_180, TRTCVideoResolution_480_270, TRTCVideoResolution_640_360, TRTCVideoResolution_960_540, TRTCVideoResolution_1280_720, TRTCVideoResolution_1920_1080, TRTCVideoResolution_640_368, TRTCVideoResolution_960_544 };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

