/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.tencent;

public final class TRTCVideoRotation {
  public final static TRTCVideoRotation TRTCVideoRotation0 = new TRTCVideoRotation("TRTCVideoRotation0", 0);
  public final static TRTCVideoRotation TRTCVideoRotation90 = new TRTCVideoRotation("TRTCVideoRotation90", 1);
  public final static TRTCVideoRotation TRTCVideoRotation180 = new TRTCVideoRotation("TRTCVideoRotation180", 2);
  public final static TRTCVideoRotation TRTCVideoRotation270 = new TRTCVideoRotation("TRTCVideoRotation270", 3);

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static TRTCVideoRotation swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + TRTCVideoRotation.class + " with value " + swigValue);
  }

  private TRTCVideoRotation(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private TRTCVideoRotation(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private TRTCVideoRotation(String swigName, TRTCVideoRotation swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static TRTCVideoRotation[] swigValues = { TRTCVideoRotation0, TRTCVideoRotation90, TRTCVideoRotation180, TRTCVideoRotation270 };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

