/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.tencent;

public class TRTCParams {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected TRTCParams(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TRTCParams obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        trtcenginewarperJNI.delete_TRTCParams(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSdkAppId(long value) {
    trtcenginewarperJNI.TRTCParams_sdkAppId_set(swigCPtr, this, value);
  }

  public long getSdkAppId() {
    return trtcenginewarperJNI.TRTCParams_sdkAppId_get(swigCPtr, this);
  }

  public void setRoomId(long value) {
    trtcenginewarperJNI.TRTCParams_roomId_set(swigCPtr, this, value);
  }

  public long getRoomId() {
    return trtcenginewarperJNI.TRTCParams_roomId_get(swigCPtr, this);
  }

  public void setUserId(StringBuffer value) {
    trtcenginewarperJNI.TRTCParams_userId_set(swigCPtr, this, StringBuffer.getCPtr(value), value);
  }

  public StringBuffer getUserId() {
    long cPtr = trtcenginewarperJNI.TRTCParams_userId_get(swigCPtr, this);
    return (cPtr == 0) ? null : new StringBuffer(cPtr, false);
  }

  public void setUserSig(StringBuffer value) {
    trtcenginewarperJNI.TRTCParams_userSig_set(swigCPtr, this, StringBuffer.getCPtr(value), value);
  }

  public StringBuffer getUserSig() {
    long cPtr = trtcenginewarperJNI.TRTCParams_userSig_get(swigCPtr, this);
    return (cPtr == 0) ? null : new StringBuffer(cPtr, false);
  }

  public void setPrivateMapKey(StringBuffer value) {
    trtcenginewarperJNI.TRTCParams_privateMapKey_set(swigCPtr, this, StringBuffer.getCPtr(value), value);
  }

  public StringBuffer getPrivateMapKey() {
    long cPtr = trtcenginewarperJNI.TRTCParams_privateMapKey_get(swigCPtr, this);
    return (cPtr == 0) ? null : new StringBuffer(cPtr, false);
  }

  public void setBusinessInfo(StringBuffer value) {
    trtcenginewarperJNI.TRTCParams_businessInfo_set(swigCPtr, this, StringBuffer.getCPtr(value), value);
  }

  public StringBuffer getBusinessInfo() {
    long cPtr = trtcenginewarperJNI.TRTCParams_businessInfo_get(swigCPtr, this);
    return (cPtr == 0) ? null : new StringBuffer(cPtr, false);
  }

  public void setClientRole(TRTCClientRole value) {
    trtcenginewarperJNI.TRTCParams_clientRole_set(swigCPtr, this, value.swigValue());
  }

  public TRTCClientRole getClientRole() {
    return TRTCClientRole.swigToEnum(trtcenginewarperJNI.TRTCParams_clientRole_get(swigCPtr, this));
  }

  public TRTCParams() {
    this(trtcenginewarperJNI.new_TRTCParams(), true);
  }

}
