/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.tencent;

public class TRTCVideoFrame {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected TRTCVideoFrame(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TRTCVideoFrame obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        trtcenginewarperJNI.delete_TRTCVideoFrame(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setVideoFormat(TRTCVideoFrameFormat value) {
    trtcenginewarperJNI.TRTCVideoFrame_videoFormat_set(swigCPtr, this, value.swigValue());
  }

  public TRTCVideoFrameFormat getVideoFormat() {
    return TRTCVideoFrameFormat.swigToEnum(trtcenginewarperJNI.TRTCVideoFrame_videoFormat_get(swigCPtr, this));
  }

  public void setBufferType(TRTCVideoBufferType value) {
    trtcenginewarperJNI.TRTCVideoFrame_bufferType_set(swigCPtr, this, value.swigValue());
  }

  public TRTCVideoBufferType getBufferType() {
    return TRTCVideoBufferType.swigToEnum(trtcenginewarperJNI.TRTCVideoFrame_bufferType_get(swigCPtr, this));
  }

  public void setData(byte[] value) {
    trtcenginewarperJNI.TRTCVideoFrame_data_set(swigCPtr, this, value);
  }

  public byte[] getData() {
    return trtcenginewarperJNI.TRTCVideoFrame_data_get(swigCPtr, this);
}

  public void setTextureId(int value) {
    trtcenginewarperJNI.TRTCVideoFrame_textureId_set(swigCPtr, this, value);
  }

  public int getTextureId() {
    return trtcenginewarperJNI.TRTCVideoFrame_textureId_get(swigCPtr, this);
  }

  public void setLength(long value) {
    trtcenginewarperJNI.TRTCVideoFrame_length_set(swigCPtr, this, value);
  }

  public long getLength() {
    return trtcenginewarperJNI.TRTCVideoFrame_length_get(swigCPtr, this);
  }

  public void setWidth(long value) {
    trtcenginewarperJNI.TRTCVideoFrame_width_set(swigCPtr, this, value);
  }

  public long getWidth() {
    return trtcenginewarperJNI.TRTCVideoFrame_width_get(swigCPtr, this);
  }

  public void setHeight(long value) {
    trtcenginewarperJNI.TRTCVideoFrame_height_set(swigCPtr, this, value);
  }

  public long getHeight() {
    return trtcenginewarperJNI.TRTCVideoFrame_height_get(swigCPtr, this);
  }

  public void setTimestamp(java.math.BigInteger value) {
    trtcenginewarperJNI.TRTCVideoFrame_timestamp_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getTimestamp() {
    return trtcenginewarperJNI.TRTCVideoFrame_timestamp_get(swigCPtr, this);
  }

  public void setRotation(TRTCVideoRotation value) {
    trtcenginewarperJNI.TRTCVideoFrame_rotation_set(swigCPtr, this, value.swigValue());
  }

  public TRTCVideoRotation getRotation() {
    return TRTCVideoRotation.swigToEnum(trtcenginewarperJNI.TRTCVideoFrame_rotation_get(swigCPtr, this));
  }

  public TRTCVideoFrame() {
    this(trtcenginewarperJNI.new_TRTCVideoFrame(), true);
  }

  public void initData(int data_length_init) {
    trtcenginewarperJNI.TRTCVideoFrame_initData(swigCPtr, this, data_length_init);
  }

  public void uninitData(int data_length_uninit) {
    trtcenginewarperJNI.TRTCVideoFrame_uninitData(swigCPtr, this, data_length_uninit);
  }

}
