/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.tencent;

public final class TRTCVideoBufferType {
  public final static TRTCVideoBufferType TRTCVideoBufferType_Unknown = new TRTCVideoBufferType("TRTCVideoBufferType_Unknown", 0);
  public final static TRTCVideoBufferType TRTCVideoBufferType_Buffer = new TRTCVideoBufferType("TRTCVideoBufferType_Buffer", 1);

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static TRTCVideoBufferType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + TRTCVideoBufferType.class + " with value " + swigValue);
  }

  private TRTCVideoBufferType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private TRTCVideoBufferType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private TRTCVideoBufferType(String swigName, TRTCVideoBufferType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static TRTCVideoBufferType[] swigValues = { TRTCVideoBufferType_Unknown, TRTCVideoBufferType_Buffer };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

