/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.tencent;

public final class TXLiteAVWarning {
  public final static TXLiteAVWarning WARNING_NET_BUSY = new TXLiteAVWarning("WARNING_NET_BUSY", 1101);
  public final static TXLiteAVWarning WARNING_RTMP_SERVER_RECONNECT = new TXLiteAVWarning("WARNING_RTMP_SERVER_RECONNECT", 1102);
  public final static TXLiteAVWarning WARNING_HW_ENCODER_START_FAIL = new TXLiteAVWarning("WARNING_HW_ENCODER_START_FAIL", 1103);
  public final static TXLiteAVWarning WARNING_VIDEO_ENCODER_SW_TO_HW = new TXLiteAVWarning("WARNING_VIDEO_ENCODER_SW_TO_HW", 1107);
  public final static TXLiteAVWarning WARNING_INSUFFICIENT_CAPTURE_FPS = new TXLiteAVWarning("WARNING_INSUFFICIENT_CAPTURE_FPS", 1108);
  public final static TXLiteAVWarning WARNING_SW_ENCODER_START_FAIL = new TXLiteAVWarning("WARNING_SW_ENCODER_START_FAIL", 1109);
  public final static TXLiteAVWarning WARNING_REDUCE_CAPTURE_RESOLUTION = new TXLiteAVWarning("WARNING_REDUCE_CAPTURE_RESOLUTION", 1110);
  public final static TXLiteAVWarning WARNING_VIDEO_FRAME_DECODE_FAIL = new TXLiteAVWarning("WARNING_VIDEO_FRAME_DECODE_FAIL", 2101);
  public final static TXLiteAVWarning WARNING_AUDIO_FRAME_DECODE_FAIL = new TXLiteAVWarning("WARNING_AUDIO_FRAME_DECODE_FAIL", 2102);
  public final static TXLiteAVWarning WARNING_LIVE_STREAM_SERVER_RECONNECT = new TXLiteAVWarning("WARNING_LIVE_STREAM_SERVER_RECONNECT", 2103);
  public final static TXLiteAVWarning WARNING_RECV_DATA_LAG = new TXLiteAVWarning("WARNING_RECV_DATA_LAG", 2104);
  public final static TXLiteAVWarning WARNING_VIDEO_PLAY_LAG = new TXLiteAVWarning("WARNING_VIDEO_PLAY_LAG", 2105);
  public final static TXLiteAVWarning WARNING_HW_DECODER_START_FAIL = new TXLiteAVWarning("WARNING_HW_DECODER_START_FAIL", 2106);
  public final static TXLiteAVWarning WARNING_VIDEO_DECODER_HW_TO_SW = new TXLiteAVWarning("WARNING_VIDEO_DECODER_HW_TO_SW", 2108);
  public final static TXLiteAVWarning WARNING_SW_DECODER_START_FAIL = new TXLiteAVWarning("WARNING_SW_DECODER_START_FAIL", 2109);
  public final static TXLiteAVWarning WARNING_RTMP_DNS_FAIL = new TXLiteAVWarning("WARNING_RTMP_DNS_FAIL", 3001);
  public final static TXLiteAVWarning WARNING_RTMP_SEVER_CONN_FAIL = new TXLiteAVWarning("WARNING_RTMP_SEVER_CONN_FAIL", 3002);
  public final static TXLiteAVWarning WARNING_RTMP_SHAKE_FAIL = new TXLiteAVWarning("WARNING_RTMP_SHAKE_FAIL", 3003);
  public final static TXLiteAVWarning WARNING_RTMP_SERVER_BREAK_CONNECT = new TXLiteAVWarning("WARNING_RTMP_SERVER_BREAK_CONNECT", 3004);
  public final static TXLiteAVWarning WARNING_RTMP_READ_WRITE_FAIL = new TXLiteAVWarning("WARNING_RTMP_READ_WRITE_FAIL", 3005);
  public final static TXLiteAVWarning WARNING_RTMP_WRITE_FAIL = new TXLiteAVWarning("WARNING_RTMP_WRITE_FAIL", 3006);
  public final static TXLiteAVWarning WARNING_RTMP_READ_FAIL = new TXLiteAVWarning("WARNING_RTMP_READ_FAIL", 3007);
  public final static TXLiteAVWarning WARNING_RTMP_NO_DATA = new TXLiteAVWarning("WARNING_RTMP_NO_DATA", 3008);
  public final static TXLiteAVWarning WARNING_PLAY_LIVE_STREAM_INFO_CONNECT_FAIL = new TXLiteAVWarning("WARNING_PLAY_LIVE_STREAM_INFO_CONNECT_FAIL", 3009);
  public final static TXLiteAVWarning WARNING_NO_STEAM_SOURCE_FAIL = new TXLiteAVWarning("WARNING_NO_STEAM_SOURCE_FAIL", 3010);
  public final static TXLiteAVWarning WARNING_ROOM_DISCONNECT = new TXLiteAVWarning("WARNING_ROOM_DISCONNECT", 5101);
  public final static TXLiteAVWarning WARNING_ROOM_RECONNECT = new TXLiteAVWarning("WARNING_ROOM_RECONNECT", 5102);
  public final static TXLiteAVWarning WARNING_ROOM_NET_BUSY = new TXLiteAVWarning("WARNING_ROOM_NET_BUSY", 5103);
  public final static TXLiteAVWarning WARNING_IGNORE_UPSTREAM_FOR_AUDIENCE = new TXLiteAVWarning("WARNING_IGNORE_UPSTREAM_FOR_AUDIENCE", 6001);

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static TXLiteAVWarning swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + TXLiteAVWarning.class + " with value " + swigValue);
  }

  private TXLiteAVWarning(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private TXLiteAVWarning(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private TXLiteAVWarning(String swigName, TXLiteAVWarning swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static TXLiteAVWarning[] swigValues = { WARNING_NET_BUSY, WARNING_RTMP_SERVER_RECONNECT, WARNING_HW_ENCODER_START_FAIL, WARNING_VIDEO_ENCODER_SW_TO_HW, WARNING_INSUFFICIENT_CAPTURE_FPS, WARNING_SW_ENCODER_START_FAIL, WARNING_REDUCE_CAPTURE_RESOLUTION, WARNING_VIDEO_FRAME_DECODE_FAIL, WARNING_AUDIO_FRAME_DECODE_FAIL, WARNING_LIVE_STREAM_SERVER_RECONNECT, WARNING_RECV_DATA_LAG, WARNING_VIDEO_PLAY_LAG, WARNING_HW_DECODER_START_FAIL, WARNING_VIDEO_DECODER_HW_TO_SW, WARNING_SW_DECODER_START_FAIL, WARNING_RTMP_DNS_FAIL, WARNING_RTMP_SEVER_CONN_FAIL, WARNING_RTMP_SHAKE_FAIL, WARNING_RTMP_SERVER_BREAK_CONNECT, WARNING_RTMP_READ_WRITE_FAIL, WARNING_RTMP_WRITE_FAIL, WARNING_RTMP_READ_FAIL, WARNING_RTMP_NO_DATA, WARNING_PLAY_LIVE_STREAM_INFO_CONNECT_FAIL, WARNING_NO_STEAM_SOURCE_FAIL, WARNING_ROOM_DISCONNECT, WARNING_ROOM_RECONNECT, WARNING_ROOM_NET_BUSY, WARNING_IGNORE_UPSTREAM_FOR_AUDIENCE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

