/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.tencent;

public final class TXLiteAVEvent {
  public final static TXLiteAVEvent EVT_RTMP_PUSH_CONNECT_SUCC = new TXLiteAVEvent("EVT_RTMP_PUSH_CONNECT_SUCC", 1001);
  public final static TXLiteAVEvent EVT_RTMP_PUSH_BEGIN = new TXLiteAVEvent("EVT_RTMP_PUSH_BEGIN", 1002);
  public final static TXLiteAVEvent EVT_CAMERA_START_SUCC = new TXLiteAVEvent("EVT_CAMERA_START_SUCC", 1003);
  public final static TXLiteAVEvent EVT_SCREEN_CAPTURE_SUCC = new TXLiteAVEvent("EVT_SCREEN_CAPTURE_SUCC", 1004);
  public final static TXLiteAVEvent EVT_UP_CHANGE_RESOLUTION = new TXLiteAVEvent("EVT_UP_CHANGE_RESOLUTION", 1005);
  public final static TXLiteAVEvent EVT_UP_CHANGE_BITRATE = new TXLiteAVEvent("EVT_UP_CHANGE_BITRATE", 1006);
  public final static TXLiteAVEvent EVT_FIRST_FRAME_AVAILABLE = new TXLiteAVEvent("EVT_FIRST_FRAME_AVAILABLE", 1007);
  public final static TXLiteAVEvent EVT_START_VIDEO_ENCODER = new TXLiteAVEvent("EVT_START_VIDEO_ENCODER", 1008);
  public final static TXLiteAVEvent EVT_SNAPSHOT_COMPLETE = new TXLiteAVEvent("EVT_SNAPSHOT_COMPLETE", 1022);
  public final static TXLiteAVEvent EVT_CAMERA_REMOVED = new TXLiteAVEvent("EVT_CAMERA_REMOVED", 1023);
  public final static TXLiteAVEvent EVT_CAMERA_AVAILABLE = new TXLiteAVEvent("EVT_CAMERA_AVAILABLE", 1024);
  public final static TXLiteAVEvent EVT_CAMERA_CLOSE = new TXLiteAVEvent("EVT_CAMERA_CLOSE", 1025);
  public final static TXLiteAVEvent EVT_RTMP_PUSH_PUBLISH_START = new TXLiteAVEvent("EVT_RTMP_PUSH_PUBLISH_START", 1026);
  public final static TXLiteAVEvent EVT_HW_ENCODER_START_SUCC = new TXLiteAVEvent("EVT_HW_ENCODER_START_SUCC", 1027);
  public final static TXLiteAVEvent EVT_SW_ENCODER_START_SUCC = new TXLiteAVEvent("EVT_SW_ENCODER_START_SUCC", 1028);
  public final static TXLiteAVEvent EVT_PLAY_LIVE_STREAM_CONNECT_SUCC = new TXLiteAVEvent("EVT_PLAY_LIVE_STREAM_CONNECT_SUCC", 2001);
  public final static TXLiteAVEvent EVT_PLAY_LIVE_STREAM_BEGIN = new TXLiteAVEvent("EVT_PLAY_LIVE_STREAM_BEGIN", 2002);
  public final static TXLiteAVEvent EVT_RENDER_FIRST_I_FRAME = new TXLiteAVEvent("EVT_RENDER_FIRST_I_FRAME", 2003);
  public final static TXLiteAVEvent EVT_VIDEO_PLAY_BEGIN = new TXLiteAVEvent("EVT_VIDEO_PLAY_BEGIN", 2004);
  public final static TXLiteAVEvent EVT_VIDEO_PLAY_PROGRESS = new TXLiteAVEvent("EVT_VIDEO_PLAY_PROGRESS", 2005);
  public final static TXLiteAVEvent EVT_VIDEO_PLAY_END = new TXLiteAVEvent("EVT_VIDEO_PLAY_END", 2006);
  public final static TXLiteAVEvent EVT_VIDEO_PLAY_LOADING = new TXLiteAVEvent("EVT_VIDEO_PLAY_LOADING", 2007);
  public final static TXLiteAVEvent EVT_START_VIDEO_DECODER = new TXLiteAVEvent("EVT_START_VIDEO_DECODER", 2008);
  public final static TXLiteAVEvent EVT_DOWN_CHANGE_RESOLUTION = new TXLiteAVEvent("EVT_DOWN_CHANGE_RESOLUTION", 2009);
  public final static TXLiteAVEvent EVT_GET_VODFILE_MEDIAINFO_SUCC = new TXLiteAVEvent("EVT_GET_VODFILE_MEDIAINFO_SUCC", 2010);
  public final static TXLiteAVEvent EVT_VIDEO_CHANGE_ROTATION = new TXLiteAVEvent("EVT_VIDEO_CHANGE_ROTATION", 2011);
  public final static TXLiteAVEvent EVT_PLAY_GET_MESSAGE = new TXLiteAVEvent("EVT_PLAY_GET_MESSAGE", 2012);
  public final static TXLiteAVEvent EVT_VOD_PLAY_PREPARED = new TXLiteAVEvent("EVT_VOD_PLAY_PREPARED", 2013);
  public final static TXLiteAVEvent EVT_VOD_PLAY_LOADING_END = new TXLiteAVEvent("EVT_VOD_PLAY_LOADING_END", 2014);
  public final static TXLiteAVEvent EVT_PLAY_LIVE_STREAM_SWITCH_SUCC = new TXLiteAVEvent("EVT_PLAY_LIVE_STREAM_SWITCH_SUCC", 2015);
  public final static TXLiteAVEvent EVT_VOD_PLAY_TCP_CONNECT_SUCC = new TXLiteAVEvent("EVT_VOD_PLAY_TCP_CONNECT_SUCC", 2016);
  public final static TXLiteAVEvent EVT_VOD_PLAY_FIRST_VIDEO_PACKET = new TXLiteAVEvent("EVT_VOD_PLAY_FIRST_VIDEO_PACKET", 2017);
  public final static TXLiteAVEvent EVT_VOD_PLAY_DNS_RESOLVED = new TXLiteAVEvent("EVT_VOD_PLAY_DNS_RESOLVED", 2018);
  public final static TXLiteAVEvent EVT_VOD_PLAY_SEEK_COMPLETE = new TXLiteAVEvent("EVT_VOD_PLAY_SEEK_COMPLETE", 2019);
  public final static TXLiteAVEvent EVT_VIDEO_DECODER_CACHE_TOO_MANY_FRAMES = new TXLiteAVEvent("EVT_VIDEO_DECODER_CACHE_TOO_MANY_FRAMES", 2020);
  public final static TXLiteAVEvent EVT_HW_DECODER_START_SUCC = new TXLiteAVEvent("EVT_HW_DECODER_START_SUCC", 2021);
  public final static TXLiteAVEvent EVT_SW_DECODER_START_SUCC = new TXLiteAVEvent("EVT_SW_DECODER_START_SUCC", 2022);
  public final static TXLiteAVEvent EVT_AUDIO_JITTER_STATE_FIRST_LOADING = new TXLiteAVEvent("EVT_AUDIO_JITTER_STATE_FIRST_LOADING", 2023);
  public final static TXLiteAVEvent EVT_AUDIO_JITTER_STATE_LOADING = new TXLiteAVEvent("EVT_AUDIO_JITTER_STATE_LOADING", 2024);
  public final static TXLiteAVEvent EVT_AUDIO_JITTER_STATE_PLAYING = new TXLiteAVEvent("EVT_AUDIO_JITTER_STATE_PLAYING", 2025);
  public final static TXLiteAVEvent EVT_AUDIO_JITTER_STATE_FIRST_PLAY = new TXLiteAVEvent("EVT_AUDIO_JITTER_STATE_FIRST_PLAY", 2026);
  public final static TXLiteAVEvent EVT_MIC_START_SUCC = new TXLiteAVEvent("EVT_MIC_START_SUCC", 2027);
  public final static TXLiteAVEvent EVT_PLAY_GET_METADATA = new TXLiteAVEvent("EVT_PLAY_GET_METADATA", 2028);
  public final static TXLiteAVEvent EVT_ROOM_ENTER = new TXLiteAVEvent("EVT_ROOM_ENTER", 1018);
  public final static TXLiteAVEvent EVT_ROOM_EXIT = new TXLiteAVEvent("EVT_ROOM_EXIT", 1019);
  public final static TXLiteAVEvent EVT_ROOM_USERLIST = new TXLiteAVEvent("EVT_ROOM_USERLIST", 1020);
  public final static TXLiteAVEvent EVT_ROOM_NEED_REENTER = new TXLiteAVEvent("EVT_ROOM_NEED_REENTER", 1021);
  public final static TXLiteAVEvent EVT_ROOM_REQUEST_IP_SUCC = new TXLiteAVEvent("EVT_ROOM_REQUEST_IP_SUCC", 8001);
  public final static TXLiteAVEvent EVT_ROOM_CONNECT_SUCC = new TXLiteAVEvent("EVT_ROOM_CONNECT_SUCC", 8002);
  public final static TXLiteAVEvent EVT_ROOM_REQUEST_AVSEAT_SUCC = new TXLiteAVEvent("EVT_ROOM_REQUEST_AVSEAT_SUCC", 8003);

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static TXLiteAVEvent swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + TXLiteAVEvent.class + " with value " + swigValue);
  }

  private TXLiteAVEvent(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private TXLiteAVEvent(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private TXLiteAVEvent(String swigName, TXLiteAVEvent swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static TXLiteAVEvent[] swigValues = { EVT_RTMP_PUSH_CONNECT_SUCC, EVT_RTMP_PUSH_BEGIN, EVT_CAMERA_START_SUCC, EVT_SCREEN_CAPTURE_SUCC, EVT_UP_CHANGE_RESOLUTION, EVT_UP_CHANGE_BITRATE, EVT_FIRST_FRAME_AVAILABLE, EVT_START_VIDEO_ENCODER, EVT_SNAPSHOT_COMPLETE, EVT_CAMERA_REMOVED, EVT_CAMERA_AVAILABLE, EVT_CAMERA_CLOSE, EVT_RTMP_PUSH_PUBLISH_START, EVT_HW_ENCODER_START_SUCC, EVT_SW_ENCODER_START_SUCC, EVT_PLAY_LIVE_STREAM_CONNECT_SUCC, EVT_PLAY_LIVE_STREAM_BEGIN, EVT_RENDER_FIRST_I_FRAME, EVT_VIDEO_PLAY_BEGIN, EVT_VIDEO_PLAY_PROGRESS, EVT_VIDEO_PLAY_END, EVT_VIDEO_PLAY_LOADING, EVT_START_VIDEO_DECODER, EVT_DOWN_CHANGE_RESOLUTION, EVT_GET_VODFILE_MEDIAINFO_SUCC, EVT_VIDEO_CHANGE_ROTATION, EVT_PLAY_GET_MESSAGE, EVT_VOD_PLAY_PREPARED, EVT_VOD_PLAY_LOADING_END, EVT_PLAY_LIVE_STREAM_SWITCH_SUCC, EVT_VOD_PLAY_TCP_CONNECT_SUCC, EVT_VOD_PLAY_FIRST_VIDEO_PACKET, EVT_VOD_PLAY_DNS_RESOLVED, EVT_VOD_PLAY_SEEK_COMPLETE, EVT_VIDEO_DECODER_CACHE_TOO_MANY_FRAMES, EVT_HW_DECODER_START_SUCC, EVT_SW_DECODER_START_SUCC, EVT_AUDIO_JITTER_STATE_FIRST_LOADING, EVT_AUDIO_JITTER_STATE_LOADING, EVT_AUDIO_JITTER_STATE_PLAYING, EVT_AUDIO_JITTER_STATE_FIRST_PLAY, EVT_MIC_START_SUCC, EVT_PLAY_GET_METADATA, EVT_ROOM_ENTER, EVT_ROOM_EXIT, EVT_ROOM_USERLIST, EVT_ROOM_NEED_REENTER, EVT_ROOM_REQUEST_IP_SUCC, EVT_ROOM_CONNECT_SUCC, EVT_ROOM_REQUEST_AVSEAT_SUCC };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

