import os

TENCENTCLOUD_SECRETID = 'AKIDTloa5JHyOWOzJM8droVv4wYu0pNq41h6'
TENCENTCLOUD_SECRETKEY = 'A3f05tQffPt63lCMFsEJ7evve6JFuIQH'
os.environ.setdefault("TENCENTCLOUD_SECRETID", TENCENTCLOUD_SECRETID)
os.environ.setdefault("TENCENTCLOUD_SECRETKEY", TENCENTCLOUD_SECRETKEY)