component: scf
name: ap-guangzhou_default_helloworld
inputs:
  name: helloworld
  src:
    src: ./src
  handler: example.Hello::mainHandler
  runtime: Java21
  namespace: default
  region: ap-guangzhou
  memorySize: 128
  timeout: 3
