component: scf
name: ap-guangzhou_default_CkafkaConnectorDataDesensitization
inputs:
  name: CkafkaConnectorDataDesensitization
  src: ./src
  handler: index.main_handler
  runtime: Python3.6
  namespace: default
  region: ap-guangzhou
  memorySize: 128
  timeout: 30